/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sample Forecast */
        post: operations["sample_forecast_api_forecast_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Custom Forecast */
        post: operations["custom_forecast_api_forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sample Plan */
        post: operations["sample_plan_api_plan_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Custom Plan */
        post: operations["custom_plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Baseline */
        post: operations["scenario_baseline_api_scenarios_baseline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Capture */
        post: operations["scenario_capture_api_scenarios_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Compare */
        post: operations["scenario_compare_api_scenarios_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Detail */
        post: operations["scenario_detail_api_scenarios_detail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_workflow_session_get"];
        put?: never;
        post?: never;
        /** Reset */
        delete: operations["reset_api_workflow_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/template/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Template */
        get: operations["download_template_api_workflow_template__size__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Import Workbook */
        put: operations["import_workbook_api_workflow_import_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/review/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review View */
        get: operations["review_view_api_workflow_review__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/review/{reference}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Plan */
        get: operations["review_plan_api_workflow_review__reference__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/review/{reference}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decision */
        post: operations["decision_api_workflow_review__reference__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/review/{reference}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rerun */
        post: operations["rerun_api_workflow_review__reference__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/review/{reference}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Final Accept */
        post: operations["final_accept_api_workflow_review__reference__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/review/{reference}/download/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_workflow_review__reference__download__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reopen */
        put: operations["reopen_api_workflow_snapshot_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/review/{reference}/new-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fork */
        post: operations["fork_api_workflow_review__reference__new_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario Draft */
        post: operations["scenario_draft_api_workflow_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/review/{reference}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Detail */
        post: operations["review_detail_api_workflow_review__reference__detail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIError */
        APIError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["Issue"][];
        };
        /** ActionChange */
        ActionChange: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "purchase" | "movement";
            /**
             * Change
             * @enum {string}
             */
            change: "added" | "removed" | "changed";
            /** Business Key */
            business_key: string;
            /** Before */
            before?: components["schemas"]["Purchase"] | components["schemas"]["Movement"] | null;
            /** After */
            after?: components["schemas"]["Purchase"] | components["schemas"]["Movement"] | null;
        };
        /** Actions */
        Actions: {
            /** Purchases */
            purchases?: components["schemas"]["Purchase"][];
            /** Movements */
            movements?: components["schemas"]["Movement"][];
        };
        /** Adjustment */
        Adjustment: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Original */
            original: number;
            /** Adjusted */
            adjusted: number;
            /** Reason */
            reason: string;
        };
        /** Assortment */
        Assortment: {
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /**
             * Ranged From
             * Format: date
             */
            ranged_from: string;
            /** Ranged To */
            ranged_to?: string | null;
            /**
             * Service Class
             * @enum {string}
             */
            service_class: "A" | "B" | "C";
            /** Must Stock */
            must_stock: boolean;
            /** Launch Daily Units */
            launch_daily_units?: number | null;
            /** Launch Known At */
            launch_known_at?: string | null;
            /** Launch Reason */
            launch_reason?: string | null;
        };
        /** Availability */
        Availability: {
            /** Supplier Id */
            supplier_id: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Remaining Fraction */
            remaining_fraction: number;
        };
        /** BaselineResult */
        BaselineResult: {
            baseline: components["schemas"]["BaselineSnapshot"];
            original: components["schemas"]["Outcome"];
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Suppliers */
            suppliers: string[];
            /** Supplier Options */
            supplier_options: components["schemas"]["SupplierOption"][];
            /** Categories */
            categories: string[];
            /** Existing Orders */
            existing_orders: {
                [key: string]: string;
            }[];
            /** Weeks */
            weeks: components["schemas"]["Funding"][];
            /** Elapsed Ms */
            elapsed_ms: number;
        };
        /** BaselineSnapshot */
        BaselineSnapshot: {
            /** Purchases */
            purchases?: components["schemas"]["Purchase"][];
            /** Movements */
            movements?: components["schemas"]["Movement"][];
            /** Size */
            size?: ("fixture" | "full") | null;
            provenance?: components["schemas"]["DatasetProvenance"] | null;
            /** Dataset Hash */
            dataset_hash: string;
            /**
             * Version
             * @default sample-scenarios-1
             * @constant
             */
            version: "sample-scenarios-1";
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** Budget */
        Budget: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** New Commitment Cap */
            new_commitment_cap: number;
            /** Payment Ceiling */
            payment_ceiling: number;
            /** Transfer Budget */
            transfer_budget: number;
        };
        /** BufferEvidence */
        BufferEvidence: {
            /** Units */
            units: number | null;
            /**
             * Method
             * @enum {string}
             */
            method: "empirical_underforecast" | "days_of_demand" | "unavailable";
            /** Protection Days */
            protection_days: number;
            /** Percentile */
            percentile: number;
            /** Sample Count */
            sample_count: number;
            /** Fallback Days */
            fallback_days: number | null;
            /** Note */
            note: string;
        };
        /** CandidateRecord */
        CandidateRecord: {
            /**
             * Method
             * @enum {string}
             */
            method: "seasonal_naive" | "weekday_mean" | "weighted_weekday_mean";
            /** Metrics */
            metrics: components["schemas"]["Metrics"][];
            /** Windows */
            windows: components["schemas"]["WindowRecord"][];
        };
        /** CaptureRequest */
        CaptureRequest: {
            /** Purchases */
            purchases?: components["schemas"]["Purchase"][];
            /** Movements */
            movements?: components["schemas"]["Movement"][];
            /** Size */
            size?: ("fixture" | "full") | null;
            /** Dataset Hash */
            dataset_hash: string;
        };
        /** CashWeek */
        CashWeek: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Commitments */
            commitments: number;
            /** Commitment Cap */
            commitment_cap: number | null;
            /** Commitment Headroom */
            commitment_headroom: number | null;
            /** Existing Payments */
            existing_payments: number;
            /** New Payments */
            new_payments: number;
            /** Total Payments */
            total_payments: number;
            /** Payment Ceiling */
            payment_ceiling: number | null;
            /** Payment Headroom */
            payment_headroom: number | null;
            /** Movement Fees */
            movement_fees: number;
            /** Transfer Budget */
            transfer_budget: number | null;
            /** Transfer Headroom */
            transfer_headroom: number | null;
        };
        /** Dataset */
        Dataset: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Dataset Id */
            dataset_id: string;
            /** Synthetic */
            synthetic: boolean;
            /** Products */
            products: components["schemas"]["Product"][];
            /** Locations */
            locations: components["schemas"]["Location"][];
            /** Assortment */
            assortment: components["schemas"]["Assortment"][];
            /** Demand History */
            demand_history: components["schemas"]["Observation"][];
            /** Inventory */
            inventory: components["schemas"]["Inventory"][];
            /** Suppliers */
            suppliers: components["schemas"]["Supplier"][];
            /** Supplier Offers */
            supplier_offers: components["schemas"]["SupplierOffer"][];
            /** Supplier Capacity */
            supplier_capacity: components["schemas"]["SupplierCapacity"][];
            /** Transfer Lanes */
            transfer_lanes: components["schemas"]["TransferLane"][];
            /** Open Orders */
            open_orders: components["schemas"]["OpenOrder"][];
            /** Open Transfers */
            open_transfers: components["schemas"]["OpenTransfer"][];
            /** Payables */
            payables: components["schemas"]["Payable"][];
            /** Budgets */
            budgets: components["schemas"]["Budget"][];
            /** Events */
            events: components["schemas"]["Event"][];
            settings: components["schemas"]["Settings"];
            /** Declared Empty */
            declared_empty: ("open_orders" | "open_transfers" | "payables")[];
        };
        /** DatasetDimensions */
        DatasetDimensions: {
            /** Products */
            products: number;
            /** Locations */
            locations: number;
            /** Assortment */
            assortment: number;
            /** History Rows */
            history_rows: number;
        };
        /** DatasetProvenance */
        DatasetProvenance: {
            /**
             * Source
             * @enum {string}
             */
            source: "bundled_fixture" | "bundled_full" | "uploaded" | "portable";
            /** Sample Size */
            sample_size?: ("fixture" | "full") | null;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Hash */
            dataset_hash: string;
            dimensions: components["schemas"]["DatasetDimensions"];
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Revision */
            revision: string;
            /** Action Id */
            action_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "rejected" | "edited_quantity" | "draft";
            /** Quantity */
            quantity?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Delay */
        Delay: {
            /** Supplier Id */
            supplier_id: string;
            /** Days */
            days: number;
            /** Existing Order Ids */
            existing_order_ids?: string[];
            /**
             * Future Paths
             * @default false
             */
            future_paths: boolean;
        };
        /** DetailRequest */
        DetailRequest: {
            baseline: components["schemas"]["BaselineSnapshot"];
            scenario?: components["schemas"]["ScenarioDefinition"];
            /**
             * Policy
             * @enum {string}
             */
            policy: "original" | "frozen" | "replanned";
            actions?: components["schemas"]["Actions"] | null;
            /** Expected Action Hash */
            expected_action_hash?: string | null;
            /** Expected Scenario Hash */
            expected_scenario_hash?: string | null;
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /** Action Id */
            action_id?: string | null;
        };
        /** Event */
        Event: {
            /** Event Id */
            event_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "sku" | "category" | "store";
            /** Scope Id */
            scope_id: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "uplift" | "replacement";
            /** Value */
            value: number;
            /** Reason */
            reason: string;
            /**
             * Known At
             * Format: date-time
             */
            known_at: string;
        };
        /** EvidenceRequest */
        EvidenceRequest: {
            /** Expected Run Id */
            expected_run_id?: string | null;
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /** Action Id */
            action_id?: string | null;
        };
        /** EvidenceTarget */
        EvidenceTarget: {
            /** Action Id */
            action_id: string;
            /** Sku */
            sku: string;
            /** Location Id */
            location_id?: string | null;
            /**
             * Basis
             * @enum {string}
             */
            basis: "earliest_shortage" | "greatest_replenishment_need" | "no_store_association";
            /** Shortage Date */
            shortage_date?: string | null;
            /** Affected Units */
            affected_units?: number | null;
        };
        /** Failure */
        Failure: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Sku */
            sku?: string | null;
            /** Location Id */
            location_id?: string | null;
            /** Supplier Id */
            supplier_id?: string | null;
            /** Day */
            day?: string | null;
            /** Action Id */
            action_id?: string | null;
        };
        /** ForecastDay */
        ForecastDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Baseline Units */
            baseline_units: number | null;
            /** Forecast Units */
            forecast_units: number | null;
            /** Provisional Tail */
            provisional_tail: boolean;
            /** Fallback */
            fallback: string | null;
            /** Event Id */
            event_id: string | null;
            /** Reason */
            reason: string | null;
        };
        /** ForecastRequest */
        ForecastRequest: {
            dataset: components["schemas"]["Dataset"];
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
        };
        /** ForecastResult */
        ForecastResult: {
            /**
             * Schema Version
             * @default 1.0.0
             */
            schema_version: string;
            /**
             * Engine Version
             * @default 0.1.0
             */
            engine_version: string;
            /** Run Id */
            run_id: string;
            /** Input Hash */
            input_hash: string;
            /** Dataset Id */
            dataset_id: string;
            /** Synthetic */
            synthetic: boolean;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Sku */
            sku: string;
            /** Product Name */
            product_name: string;
            /** Location Id */
            location_id: string;
            /** Location Name */
            location_name: string;
            /**
             * Selected Method
             * @enum {string}
             */
            selected_method: "seasonal_naive" | "weekday_mean" | "weighted_weekday_mean";
            /**
             * Status
             * @enum {string}
             */
            status: "evaluated" | "provisional" | "unavailable";
            /** Selection Reason */
            selection_reason: string;
            /**
             * Selection Cutoff
             * Format: date
             */
            selection_cutoff: string;
            /** Improvement Pct */
            improvement_pct: number | null;
            /** Selection */
            selection: components["schemas"]["CandidateRecord"][];
            /** Final Check */
            final_check: components["schemas"]["CandidateRecord"][];
            /** Forecast */
            forecast: components["schemas"]["ForecastDay"][];
            /** History */
            history: components["schemas"]["HistoryDay"][];
            /** Visible Units */
            visible_units: number | null;
            /** Tail Units */
            tail_units: number | null;
            buffer: components["schemas"]["BufferEvidence"];
            /** Warnings */
            warnings: components["schemas"]["Issue"][];
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Evaluation Policy */
            evaluation_policy: string;
        };
        /** ForecastTrace */
        ForecastTrace: {
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /** Run Id */
            run_id: string;
            /** Input Hash */
            input_hash: string;
            /** Method */
            method: string;
            /** Status */
            status: string;
            buffer: components["schemas"]["BufferEvidence"];
        };
        /** Funding */
        Funding: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Commitment */
            commitment?: number | null;
            /** Payment */
            payment?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryDay */
        HistoryDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Observed Sales */
            observed_sales: number | null;
            /** Training Estimate */
            training_estimate: number | null;
            /** Status */
            status: string;
        };
        /** ImportResult */
        ImportResult: {
            reference?: components["schemas"]["ObjectReference"] | null;
            catalog?: components["schemas"]["SampleCatalog"] | null;
            /** Issues */
            issues: components["schemas"]["WorkbookIssue"][];
            /** Measurements */
            measurements?: {
                [key: string]: unknown;
            };
            /** Input Hash */
            input_hash?: string | null;
            provenance?: components["schemas"]["DatasetProvenance"] | null;
        };
        /** Inventory */
        Inventory: {
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** On Hand */
            on_hand: number;
            /** Blocked */
            blocked: number;
            /** Reserved */
            reserved: number;
            /** Book Unit Cost */
            book_unit_cost: number;
        };
        /** Issue */
        Issue: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /** Location */
        Location: {
            /** Location Id */
            location_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dc" | "store";
            /** Storage Volume */
            storage_volume: number;
            /** Open Weekdays */
            open_weekdays: number[];
        };
        /** Metrics */
        Metrics: {
            /** Horizon */
            horizon: number;
            /** Windows */
            windows: number;
            /** Complete Windows */
            complete_windows: number;
            /** Valid Observations */
            valid_observations: number;
            /** Excluded Observations */
            excluded_observations: number;
            /** Excluded By Reason */
            excluded_by_reason: {
                [key: string]: number;
            };
            /** Absolute Error */
            absolute_error: number | null;
            /** Actual Units */
            actual_units: number;
            /** Wape */
            wape: number | null;
            /** Signed Bias Units */
            signed_bias_units: number | null;
            /** Signed Bias Pct */
            signed_bias_pct: number | null;
            /** Mean Absolute Quantity Error */
            mean_absolute_quantity_error: number | null;
            /** Mean Quantity Bias */
            mean_quantity_bias: number | null;
        };
        /** Movement */
        Movement: {
            /** Action Id */
            action_id: string;
            /** Sku */
            sku: string;
            /** Source */
            source: string;
            /** Destination */
            destination: string;
            /** Units */
            units: number;
            /**
             * Dispatch Date
             * Format: date
             */
            dispatch_date: string;
            /**
             * Arrival Date
             * Format: date
             */
            arrival_date: string;
            /**
             * Reason
             * @default Allocate dated shared stock to store demand within donor protection.
             */
            reason: string;
        };
        /** ObjectReference */
        ObjectReference: {
            /** Object Id */
            object_id: string;
            /**
             * Driver
             * @default local
             * @enum {string}
             */
            driver: "local" | "object";
        };
        /** Observation */
        Observation: {
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Sales Units */
            sales_units: number | null;
            /** Is Open */
            is_open: boolean;
            /** Stock Available */
            stock_available: boolean | null;
            /** Event Id */
            event_id?: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
        };
        /** OpenOrder */
        OpenOrder: {
            /** External Id */
            external_id: string;
            /** Sku */
            sku: string;
            /** Supplier Id */
            supplier_id: string;
            /** Destination */
            destination: string;
            /** Remaining Units */
            remaining_units: number;
            /**
             * Order Date
             * Format: date
             */
            order_date: string;
            /**
             * Dispatch Date
             * Format: date
             */
            dispatch_date: string;
            /**
             * Arrival Date
             * Format: date
             */
            arrival_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "confirmed" | "dispatched" | "received";
            /** Cost Per Base Unit */
            cost_per_base_unit: number;
        };
        /** OpenTransfer */
        OpenTransfer: {
            /** External Id */
            external_id: string;
            /** Sku */
            sku: string;
            /** Source */
            source: string;
            /** Destination */
            destination: string;
            /** Remaining Units */
            remaining_units: number;
            /**
             * Dispatch Date
             * Format: date
             */
            dispatch_date: string;
            /**
             * Arrival Date
             * Format: date
             */
            arrival_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "confirmed" | "dispatched" | "received";
        };
        /** Outcome */
        Outcome: {
            /** Purchases */
            purchases?: components["schemas"]["Purchase"][];
            /** Movements */
            movements?: components["schemas"]["Movement"][];
            /**
             * Policy
             * @enum {string}
             */
            policy: "original" | "frozen" | "replanned";
            /** Assumptions Hash */
            assumptions_hash: string;
            /** Action Hash */
            action_hash: string;
            /** Feasible */
            feasible: boolean;
            /** Status */
            status: string;
            summary: components["schemas"]["Summary"] | null;
            /** Cash */
            cash: components["schemas"]["CashWeek"][];
            /** Failures */
            failures: components["schemas"]["Failure"][];
            /** Shortages */
            shortages: components["schemas"]["Service"][];
            /**
             * Explanations
             * @default []
             */
            explanations: components["schemas"]["Failure"][];
            /**
             * Stages
             * @default []
             */
            stages: components["schemas"]["SolverStage"][];
            /**
             * Evidence Targets
             * @default []
             */
            evidence_targets: components["schemas"]["EvidenceTarget"][];
        };
        /** Payable */
        Payable: {
            /** External Id */
            external_id: string;
            /** Linked External Id */
            linked_external_id: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Amount */
            amount: number;
        };
        /** Payment */
        Payment: {
            /** Reference */
            reference: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "existing" | "deposit" | "balance" | "movement";
            /** Amount */
            amount: number;
        };
        /** PlanRequest */
        PlanRequest: {
            dataset: components["schemas"]["Dataset"];
        };
        /** PlanResult */
        PlanResult: {
            /**
             * Stock Detail
             * @default complete
             * @enum {string}
             */
            stock_detail: "complete" | "on_demand";
            /** Stock Row Count */
            stock_row_count?: number | null;
            provenance?: components["schemas"]["DatasetProvenance"] | null;
            /** Review Id */
            review_id?: string | null;
            /** Run Id */
            run_id: string;
            /** Input Hash */
            input_hash: string;
            /** Dataset Id */
            dataset_id: string;
            /** Synthetic */
            synthetic: boolean;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Horizon Days
             * @default 56
             */
            horizon_days: number;
            /**
             * Visible Days
             * @default 28
             */
            visible_days: number;
            /**
             * Release Days
             * @default 7
             */
            release_days: number;
            /**
             * Payment Through
             * Format: date
             */
            payment_through: string;
            /**
             * Engine Version
             * @default planning-0.2.0
             */
            engine_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "feasible" | "feasible_fallback" | "invalid_inputs" | "invalid_plan";
            proposed?: components["schemas"]["PolicyResult"] | null;
            benchmark?: components["schemas"]["PolicyResult"] | null;
            no_action?: components["schemas"]["PolicyResult"] | null;
            /**
             * Forecasts
             * @default []
             */
            forecasts: components["schemas"]["ForecastTrace"][];
            /**
             * Stages
             * @default []
             */
            stages: components["schemas"]["SolverStage"][];
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["Issue"][];
            /**
             * Failures
             * @default []
             */
            failures: components["schemas"]["Failure"][];
            /**
             * Exceptions
             * @default []
             */
            exceptions: components["schemas"]["Failure"][];
            /**
             * Assumptions
             * @default []
             */
            assumptions: string[];
            /** Challenger Budget Seconds */
            challenger_budget_seconds: number;
            /** Elapsed Ms */
            elapsed_ms: number;
        };
        /** PlanSampleRequest */
        PlanSampleRequest: {
            /**
             * Size
             * @default fixture
             * @enum {string}
             */
            size: "fixture" | "full";
        };
        /** PolicyResult */
        PolicyResult: {
            /** Name */
            name: string;
            /** Purchases */
            purchases: components["schemas"]["Purchase"][];
            /** Movements */
            movements: components["schemas"]["Movement"][];
            replay: components["schemas"]["Replay"];
            /**
             * Evidence Targets
             * @default []
             */
            evidence_targets: components["schemas"]["EvidenceTarget"][];
        };
        /** Product */
        Product: {
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /**
             * Base Unit
             * @default unit
             * @constant
             */
            base_unit: "unit";
            /** Case Size */
            case_size: number;
            /** Volume Per Unit */
            volume_per_unit: number;
            /** Cost Per Base Unit */
            cost_per_base_unit: number;
            /** Net Price Per Base Unit */
            net_price_per_base_unit: number;
            /** Category */
            category: string;
            /**
             * Active From
             * Format: date
             */
            active_from: string;
            /** Active To */
            active_to?: string | null;
        };
        /** Purchase */
        Purchase: {
            /** Action Id */
            action_id: string;
            /** Offer Id */
            offer_id: string;
            /** Sku */
            sku: string;
            /** Supplier Id */
            supplier_id: string;
            /** Destination */
            destination: string;
            /** Units */
            units: number;
            /**
             * Order Date
             * Format: date
             */
            order_date: string;
            /**
             * Dispatch Date
             * Format: date
             */
            dispatch_date: string;
            /**
             * Arrival Date
             * Format: date
             */
            arrival_date: string;
            /** Value */
            value: number;
            /**
             * Reason
             * @default Supply network demand and store protection buffers.
             */
            reason: string;
        };
        /** Replay */
        Replay: {
            /** Feasible */
            feasible: boolean;
            /** Failures */
            failures: components["schemas"]["Failure"][];
            summary: components["schemas"]["Summary"];
            /** Cash */
            cash: components["schemas"]["CashWeek"][];
            /** Payments */
            payments: components["schemas"]["Payment"][];
            /** Service */
            service: components["schemas"]["Service"][];
            /** Service Groups */
            service_groups: components["schemas"]["ServiceGroup"][];
            /** Stock */
            stock: components["schemas"]["StockDay"][];
        };
        /** ReviewView */
        ReviewView: {
            /** Reference */
            reference: string;
            /** Revision */
            revision: string;
            /** State */
            state: string;
            /** Decisions */
            decisions: {
                [key: string]: unknown;
            }[];
            /** Failures */
            failures: {
                [key: string]: unknown;
            }[];
            /** Accepted Version */
            accepted_version?: string | null;
            /** Measurements */
            measurements?: {
                [key: string]: unknown;
            };
            /** Dataset Ref */
            dataset_ref?: string | null;
            provenance?: components["schemas"]["DatasetProvenance"] | null;
        };
        /** RevisionRequest */
        RevisionRequest: {
            /** Revision */
            revision: string;
            /**
             * Acknowledge Shortfalls
             * @default false
             */
            acknowledge_shortfalls: boolean;
        };
        /** SampleCatalog */
        SampleCatalog: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Products */
            products: components["schemas"]["Product"][];
            /** Locations */
            locations: components["schemas"]["Location"][];
            /** History Rows */
            history_rows: number;
            /** Warnings */
            warnings: components["schemas"]["Issue"][];
        };
        /** SampleRequest */
        SampleRequest: {
            /**
             * Size
             * @default fixture
             * @enum {string}
             */
            size: "fixture" | "full";
            /**
             * Sku
             * @default SKU001
             */
            sku: string;
            /**
             * Location Id
             * @default S1
             */
            location_id: string;
        };
        /** ScenarioDefinition */
        ScenarioDefinition: {
            /** Uplifts */
            uplifts?: components["schemas"]["Uplift"][];
            /** Delays */
            delays?: components["schemas"]["Delay"][];
            /** Availability */
            availability?: components["schemas"]["Availability"][];
            /** Funding */
            funding?: components["schemas"]["Funding"][];
        };
        /** ScenarioDetail */
        ScenarioDetail: {
            /** Review Id */
            review_id?: string | null;
            /** Plan Run Id */
            plan_run_id?: string | null;
            /** Review Revision */
            review_revision?: string | null;
            provenance: components["schemas"]["DatasetProvenance"];
            /** Baseline Id */
            baseline_id: string;
            /** Scenario Hash */
            scenario_hash: string;
            /** Assumptions Hash */
            assumptions_hash: string;
            /** Action Hash */
            action_hash: string;
            /** Policy */
            policy: string;
            /** Feasible */
            feasible: boolean;
            /** Failures */
            failures: components["schemas"]["Failure"][];
            forecast: components["schemas"]["ForecastResult"];
            /** Forecast Version */
            forecast_version: string;
            policy_buffer: components["schemas"]["BufferEvidence"];
            /** Adjustments */
            adjustments: components["schemas"]["Adjustment"][];
            /** Stock */
            stock: components["schemas"]["StockDay"][];
            /** Cash */
            cash: components["schemas"]["CashWeek"][];
            /** Payments */
            payments: components["schemas"]["Payment"][];
            /** Purchases */
            purchases: components["schemas"]["Purchase"][];
            /** Movements */
            movements: components["schemas"]["Movement"][];
            /** Confirmed Receipts */
            confirmed_receipts: {
                [key: string]: string;
            }[];
            /** Shortages */
            shortages: components["schemas"]["Service"][];
            /** Elapsed Ms */
            elapsed_ms: number;
            /**
             * Note
             * @default Stock is pooled by SKU/location. Related receipts and movements are evidence of shared availability, not one-to-one dependencies. Invalid policies suppress stock/service arithmetic; cash retains attempted obligations.
             */
            note: string;
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            baseline: components["schemas"]["BaselineSnapshot"];
            scenario?: components["schemas"]["ScenarioDefinition"];
        };
        /** ScenarioResult */
        ScenarioResult: {
            provenance: components["schemas"]["DatasetProvenance"];
            /** Baseline Id */
            baseline_id: string;
            /** Scenario Hash */
            scenario_hash: string;
            definition: components["schemas"]["ScenarioDefinition"];
            /** Changes */
            changes: string[];
            original: components["schemas"]["Outcome"];
            frozen: components["schemas"]["Outcome"];
            replanned: components["schemas"]["Outcome"];
            /** Shock Delta */
            shock_delta: {
                [key: string]: number | null;
            };
            /** Replan Delta */
            replan_delta: {
                [key: string]: number | null;
            };
            /** Forecast Versions */
            forecast_versions: {
                [key: string]: string;
            };
            /** Action Changes */
            action_changes: components["schemas"]["ActionChange"][];
            /** Elapsed Ms */
            elapsed_ms: number;
            /**
             * Note
             * @default Deltas are later minus earlier: frozen − original (shock), replanned − frozen (replanning). Invalid policies have unavailable outcome metrics. Cash shows attempted obligations even when infeasible.
             */
            note: string;
        };
        /** Service */
        Service: {
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /** Service Class */
            service_class: string;
            /** Must Stock */
            must_stock: boolean;
            /** Demand */
            demand: number;
            /** Fulfilled */
            fulfilled: number;
            /** Unmet */
            unmet: number;
            /** Tail Unmet */
            tail_unmet: number;
            /** Fill Pct */
            fill_pct: number | null;
            /** Target */
            target: number;
            /** Buffer Units */
            buffer_units: number;
            /** Unconstrained Need */
            unconstrained_need: number;
            /** Reason Codes */
            reason_codes: string[];
            /** Reason Summary */
            reason_summary?: string | null;
            /**
             * Shortage Evidence
             * @default []
             */
            shortage_evidence: components["schemas"]["ShortageEvidence"][];
        };
        /** ServiceGroup */
        ServiceGroup: {
            /** Location Id */
            location_id: string;
            /** Service Class */
            service_class: string;
            /** Must Stock */
            must_stock: boolean;
            /**
             * Window
             * @enum {string}
             */
            window: "visible" | "tail";
            /** Demand */
            demand: number;
            /** Fulfilled */
            fulfilled: number;
            /** Target */
            target: number;
            /** Target Shortfall */
            target_shortfall: number;
        };
        /** Settings */
        Settings: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * History Days
             * @default 420
             */
            history_days: number;
            /**
             * Timezone
             * @default Asia/Riyadh
             * @constant
             */
            timezone: "Asia/Riyadh";
            /**
             * Currency
             * @default SAR
             * @constant
             */
            currency: "SAR";
            /**
             * Visible Days
             * @default 28
             * @constant
             */
            visible_days: 28;
            /**
             * Horizon Days
             * @default 56
             * @constant
             */
            horizon_days: 56;
            /**
             * Release Days
             * @default 7
             * @constant
             */
            release_days: 7;
            /**
             * Review Period Days
             * @default 7
             * @constant
             */
            review_period_days: 7;
            /**
             * Protection Days
             * @default 14
             */
            protection_days: number;
            /**
             * Buffer Percentile
             * @default 90
             */
            buffer_percentile: number;
            /**
             * Fallback Buffer Days
             * @default 3
             */
            fallback_buffer_days: number;
            /**
             * Annual Holding Rate
             * @default 0.2
             */
            annual_holding_rate: number;
            /** Class Targets */
            class_targets?: {
                [key: string]: number;
            };
            /**
             * Funding Mode
             * @default funded
             * @enum {string}
             */
            funding_mode: "funded" | "unfunded_exploration";
        };
        /** ShortageEvidence */
        ShortageEvidence: {
            /**
             * Window
             * @enum {string}
             */
            window: "visible" | "tail";
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Quantity */
            quantity: number;
            /**
             * Status
             * @enum {string}
             */
            status: "established_limit" | "uncertain" | "bounded_summary";
            /** Reason Codes */
            reason_codes: string[];
            /** Detail */
            detail: string;
        };
        /** SolverStage */
        SolverStage: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Objective */
            objective?: number | null;
            /** Gap */
            gap?: number | null;
            /** Elapsed Ms */
            elapsed_ms: number;
        };
        /** StockDay */
        StockDay: {
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Opening */
            opening: number;
            /** Receipts */
            receipts: number;
            /** Demand */
            demand: number;
            /** Fulfilled */
            fulfilled: number;
            /** Unmet */
            unmet: number;
            /** Dispatched */
            dispatched: number;
            /** Closing */
            closing: number;
        };
        /** Summary */
        Summary: {
            /** Demand */
            demand: number;
            /** Fulfilled */
            fulfilled: number;
            /** Unmet */
            unmet: number;
            /** Fill Pct */
            fill_pct: number | null;
            /** Tail Demand */
            tail_demand: number;
            /** Tail Unmet */
            tail_unmet: number;
            /** Commitments */
            commitments: number;
            /** Visible Commitments */
            visible_commitments: number;
            /** Tail Commitments */
            tail_commitments: number;
            /** Payments */
            payments: number;
            /** Visible Payments */
            visible_payments: number;
            /** Later Payments */
            later_payments: number;
            /** Movement Expense */
            movement_expense: number;
            /** Ending Stock */
            ending_stock: number;
            /** Ending Inventory Investment */
            ending_inventory_investment: number;
            /** Revenue Exposure */
            revenue_exposure: number;
            /** Weekly Buffer Deficit */
            weekly_buffer_deficit: number;
            /** Terminal Excess Units */
            terminal_excess_units: number;
        };
        /** Supplier */
        Supplier: {
            /** Supplier Id */
            supplier_id: string;
            /** Name */
            name: string;
            /** Minimum Order Value */
            minimum_order_value: number;
            /** Shared Daily Capacity */
            shared_daily_capacity?: number | null;
            /** Shared Capacity Unit */
            shared_capacity_unit?: ("base_units" | "volume") | null;
        };
        /** SupplierCapacity */
        SupplierCapacity: {
            /** Supplier Id */
            supplier_id: string;
            /** Sku */
            sku: string;
            /**
             * Dispatch Date
             * Format: date
             */
            dispatch_date: string;
            /** Available Units */
            available_units: number;
            /** Shared Limit Reference */
            shared_limit_reference?: string | null;
        };
        /** SupplierOffer */
        SupplierOffer: {
            /** Offer Id */
            offer_id: string;
            /** Supplier Id */
            supplier_id: string;
            /** Sku */
            sku: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date
             */
            valid_to: string;
            /** Price Per Base Unit */
            price_per_base_unit: number;
            /** Case Size */
            case_size: number;
            /** Moq Units */
            moq_units: number;
            /** Lead Time Days */
            lead_time_days: number;
            /** Dispatch Weekdays */
            dispatch_weekdays: number[];
            /** Order Weekdays */
            order_weekdays: number[];
            /** Deposit Fraction */
            deposit_fraction: number;
            /** Balance Days After Receipt */
            balance_days_after_receipt: number;
        };
        /** SupplierOption */
        SupplierOption: {
            /** Supplier Id */
            supplier_id: string;
            /** Name */
            name: string;
            /** Existing Order Ids */
            existing_order_ids: string[];
            /** Future Paths */
            future_paths: boolean;
        };
        /** TransferLane */
        TransferLane: {
            /** Source */
            source: string;
            /** Destination */
            destination: string;
            /**
             * Transit Days
             * @enum {integer}
             */
            transit_days: 1 | 2;
            /** Dispatch Weekdays */
            dispatch_weekdays: number[];
            /** Capacity Units */
            capacity_units: number | null;
            /** Grouped Dispatch Fee */
            grouped_dispatch_fee: number;
            /** Pack Units */
            pack_units: number;
            /** Allowed Skus */
            allowed_skus: string[];
        };
        /** Uplift */
        Uplift: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "sku" | "category" | "store";
            /** Scope Id */
            scope_id: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Percent */
            percent: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindowRecord */
        WindowRecord: {
            /**
             * Origin
             * Format: date
             */
            origin: string;
            /** Horizon */
            horizon: number;
            /** Complete */
            complete: boolean;
            /** Valid Observations */
            valid_observations: number;
            /** Excluded By Reason */
            excluded_by_reason: {
                [key: string]: number;
            };
            /** Actual Units */
            actual_units: number;
            /** Forecast Units */
            forecast_units: number;
            /** Absolute Error */
            absolute_error: number;
            /** Signed Error */
            signed_error: number;
            /** Underforecast Units */
            underforecast_units: number | null;
        };
        /** WorkbookIssue */
        WorkbookIssue: {
            /** Sheet */
            sheet: string;
            /** Row */
            row?: number | null;
            /** Field */
            field?: string | null;
            /**
             * Severity
             * @default error
             */
            severity: string;
            /** Code */
            code: string;
            /** Guidance */
            guidance: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    catalog_api_sample_get: {
        parameters: {
            query?: {
                size?: "fixture" | "full";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleCatalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_forecast_api_forecast_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    custom_forecast_api_forecast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    sample_plan_api_plan_sample_post: {
        parameters: {
            query?: {
                include_stock?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanSampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    custom_plan_api_plan_post: {
        parameters: {
            query?: {
                include_stock?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    scenario_baseline_api_scenarios_baseline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanSampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    scenario_capture_api_scenarios_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    scenario_compare_api_scenarios_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    scenario_detail_api_scenarios_detail_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    session_api_workflow_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    reset_api_workflow_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    download_template_api_workflow_template__size__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                size: "blank" | "fixture";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_workbook_api_workflow_import_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
        };
    };
    review_view_api_workflow_review__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_plan_api_workflow_review__reference__plan_get: {
        parameters: {
            query?: {
                include_stock?: boolean;
            };
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_api_workflow_review__reference__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_api_workflow_review__reference__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    final_accept_api_workflow_review__reference__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_workflow_review__reference__download__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
                kind: "workbook" | "snapshot";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_api_workflow_snapshot_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
        };
    };
    fork_api_workflow_review__reference__new_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_draft_api_workflow_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_detail_api_workflow_review__reference__detail_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
