/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sample Forecast */
        post: operations["sample_forecast_api_forecast_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Custom Forecast */
        post: operations["custom_forecast_api_forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIError */
        APIError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["Issue"][];
        };
        /** Assortment */
        Assortment: {
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /**
             * Ranged From
             * Format: date
             */
            ranged_from: string;
            /** Ranged To */
            ranged_to?: string | null;
            /**
             * Service Class
             * @enum {string}
             */
            service_class: "A" | "B" | "C";
            /** Must Stock */
            must_stock: boolean;
            /** Launch Daily Units */
            launch_daily_units?: number | null;
            /** Launch Known At */
            launch_known_at?: string | null;
            /** Launch Reason */
            launch_reason?: string | null;
        };
        /** Budget */
        Budget: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** New Commitment Cap */
            new_commitment_cap: number;
            /** Payment Ceiling */
            payment_ceiling: number;
            /** Transfer Budget */
            transfer_budget: number;
        };
        /** BufferEvidence */
        BufferEvidence: {
            /** Units */
            units: number | null;
            /**
             * Method
             * @enum {string}
             */
            method: "empirical_underforecast" | "days_of_demand" | "unavailable";
            /** Protection Days */
            protection_days: number;
            /** Percentile */
            percentile: number;
            /** Sample Count */
            sample_count: number;
            /** Fallback Days */
            fallback_days: number | null;
            /** Note */
            note: string;
        };
        /** CandidateRecord */
        CandidateRecord: {
            /**
             * Method
             * @enum {string}
             */
            method: "seasonal_naive" | "weekday_mean" | "weighted_weekday_mean";
            /** Metrics */
            metrics: components["schemas"]["Metrics"][];
            /** Windows */
            windows: components["schemas"]["WindowRecord"][];
        };
        /** Dataset */
        Dataset: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Dataset Id */
            dataset_id: string;
            /** Synthetic */
            synthetic: boolean;
            /** Products */
            products: components["schemas"]["Product"][];
            /** Locations */
            locations: components["schemas"]["Location"][];
            /** Assortment */
            assortment: components["schemas"]["Assortment"][];
            /** Demand History */
            demand_history: components["schemas"]["Observation"][];
            /** Inventory */
            inventory: components["schemas"]["Inventory"][];
            /** Suppliers */
            suppliers: components["schemas"]["Supplier"][];
            /** Supplier Offers */
            supplier_offers: components["schemas"]["SupplierOffer"][];
            /** Supplier Capacity */
            supplier_capacity: components["schemas"]["SupplierCapacity"][];
            /** Transfer Lanes */
            transfer_lanes: components["schemas"]["TransferLane"][];
            /** Open Orders */
            open_orders: components["schemas"]["OpenOrder"][];
            /** Open Transfers */
            open_transfers: components["schemas"]["OpenTransfer"][];
            /** Payables */
            payables: components["schemas"]["Payable"][];
            /** Budgets */
            budgets: components["schemas"]["Budget"][];
            /** Events */
            events: components["schemas"]["Event"][];
            settings: components["schemas"]["Settings"];
            /** Declared Empty */
            declared_empty: ("open_orders" | "open_transfers" | "payables")[];
        };
        /** Event */
        Event: {
            /** Event Id */
            event_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "sku" | "category" | "store";
            /** Scope Id */
            scope_id: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "uplift" | "replacement";
            /** Value */
            value: number;
            /** Reason */
            reason: string;
            /**
             * Known At
             * Format: date-time
             */
            known_at: string;
        };
        /** ForecastDay */
        ForecastDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Baseline Units */
            baseline_units: number | null;
            /** Forecast Units */
            forecast_units: number | null;
            /** Provisional Tail */
            provisional_tail: boolean;
            /** Fallback */
            fallback: string | null;
            /** Event Id */
            event_id: string | null;
            /** Reason */
            reason: string | null;
        };
        /** ForecastRequest */
        ForecastRequest: {
            dataset: components["schemas"]["Dataset"];
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
        };
        /** ForecastResult */
        ForecastResult: {
            /**
             * Schema Version
             * @default 1.0.0
             */
            schema_version: string;
            /**
             * Engine Version
             * @default 0.1.0
             */
            engine_version: string;
            /** Run Id */
            run_id: string;
            /** Input Hash */
            input_hash: string;
            /** Dataset Id */
            dataset_id: string;
            /** Synthetic */
            synthetic: boolean;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Sku */
            sku: string;
            /** Product Name */
            product_name: string;
            /** Location Id */
            location_id: string;
            /** Location Name */
            location_name: string;
            /**
             * Selected Method
             * @enum {string}
             */
            selected_method: "seasonal_naive" | "weekday_mean" | "weighted_weekday_mean";
            /**
             * Status
             * @enum {string}
             */
            status: "evaluated" | "provisional" | "unavailable";
            /** Selection Reason */
            selection_reason: string;
            /**
             * Selection Cutoff
             * Format: date
             */
            selection_cutoff: string;
            /** Improvement Pct */
            improvement_pct: number | null;
            /** Selection */
            selection: components["schemas"]["CandidateRecord"][];
            /** Final Check */
            final_check: components["schemas"]["CandidateRecord"][];
            /** Forecast */
            forecast: components["schemas"]["ForecastDay"][];
            /** History */
            history: components["schemas"]["HistoryDay"][];
            /** Visible Units */
            visible_units: number | null;
            /** Tail Units */
            tail_units: number | null;
            buffer: components["schemas"]["BufferEvidence"];
            /** Warnings */
            warnings: components["schemas"]["Issue"][];
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Evaluation Policy */
            evaluation_policy: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryDay */
        HistoryDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Observed Sales */
            observed_sales: number | null;
            /** Training Estimate */
            training_estimate: number | null;
            /** Status */
            status: string;
        };
        /** Inventory */
        Inventory: {
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** On Hand */
            on_hand: number;
            /** Blocked */
            blocked: number;
            /** Reserved */
            reserved: number;
            /** Book Unit Cost */
            book_unit_cost: number;
        };
        /** Issue */
        Issue: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /** Location */
        Location: {
            /** Location Id */
            location_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dc" | "store";
            /** Storage Volume */
            storage_volume: number;
            /** Open Weekdays */
            open_weekdays: number[];
        };
        /** Metrics */
        Metrics: {
            /** Horizon */
            horizon: number;
            /** Windows */
            windows: number;
            /** Complete Windows */
            complete_windows: number;
            /** Valid Observations */
            valid_observations: number;
            /** Excluded Observations */
            excluded_observations: number;
            /** Excluded By Reason */
            excluded_by_reason: {
                [key: string]: number;
            };
            /** Absolute Error */
            absolute_error: number | null;
            /** Actual Units */
            actual_units: number;
            /** Wape */
            wape: number | null;
            /** Signed Bias Units */
            signed_bias_units: number | null;
            /** Signed Bias Pct */
            signed_bias_pct: number | null;
            /** Mean Absolute Quantity Error */
            mean_absolute_quantity_error: number | null;
            /** Mean Quantity Bias */
            mean_quantity_bias: number | null;
        };
        /** Observation */
        Observation: {
            /** Sku */
            sku: string;
            /** Location Id */
            location_id: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Sales Units */
            sales_units: number | null;
            /** Is Open */
            is_open: boolean;
            /** Stock Available */
            stock_available: boolean | null;
            /** Event Id */
            event_id?: string | null;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
        };
        /** OpenOrder */
        OpenOrder: {
            /** External Id */
            external_id: string;
            /** Sku */
            sku: string;
            /** Supplier Id */
            supplier_id: string;
            /** Destination */
            destination: string;
            /** Remaining Units */
            remaining_units: number;
            /**
             * Order Date
             * Format: date
             */
            order_date: string;
            /**
             * Dispatch Date
             * Format: date
             */
            dispatch_date: string;
            /**
             * Arrival Date
             * Format: date
             */
            arrival_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "confirmed" | "dispatched" | "received";
            /** Cost Per Base Unit */
            cost_per_base_unit: number;
        };
        /** OpenTransfer */
        OpenTransfer: {
            /** External Id */
            external_id: string;
            /** Sku */
            sku: string;
            /** Source */
            source: string;
            /** Destination */
            destination: string;
            /** Remaining Units */
            remaining_units: number;
            /**
             * Dispatch Date
             * Format: date
             */
            dispatch_date: string;
            /**
             * Arrival Date
             * Format: date
             */
            arrival_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "confirmed" | "dispatched" | "received";
        };
        /** Payable */
        Payable: {
            /** External Id */
            external_id: string;
            /** Linked External Id */
            linked_external_id: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Amount */
            amount: number;
        };
        /** Product */
        Product: {
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /**
             * Base Unit
             * @default unit
             * @constant
             */
            base_unit: "unit";
            /** Case Size */
            case_size: number;
            /** Volume Per Unit */
            volume_per_unit: number;
            /** Cost Per Base Unit */
            cost_per_base_unit: number;
            /** Net Price Per Base Unit */
            net_price_per_base_unit: number;
            /** Category */
            category: string;
            /**
             * Active From
             * Format: date
             */
            active_from: string;
            /** Active To */
            active_to?: string | null;
        };
        /** SampleCatalog */
        SampleCatalog: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Products */
            products: components["schemas"]["Product"][];
            /** Locations */
            locations: components["schemas"]["Location"][];
            /** History Rows */
            history_rows: number;
            /** Warnings */
            warnings: components["schemas"]["Issue"][];
        };
        /** SampleRequest */
        SampleRequest: {
            /**
             * Size
             * @default fixture
             * @enum {string}
             */
            size: "fixture" | "full";
            /**
             * Sku
             * @default SKU001
             */
            sku: string;
            /**
             * Location Id
             * @default S1
             */
            location_id: string;
        };
        /** Settings */
        Settings: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * History Days
             * @default 420
             */
            history_days: number;
            /**
             * Timezone
             * @default Asia/Riyadh
             * @constant
             */
            timezone: "Asia/Riyadh";
            /**
             * Currency
             * @default SAR
             * @constant
             */
            currency: "SAR";
            /**
             * Visible Days
             * @default 28
             * @constant
             */
            visible_days: 28;
            /**
             * Horizon Days
             * @default 56
             * @constant
             */
            horizon_days: 56;
            /**
             * Release Days
             * @default 7
             * @constant
             */
            release_days: 7;
            /**
             * Review Period Days
             * @default 7
             * @constant
             */
            review_period_days: 7;
            /**
             * Protection Days
             * @default 14
             */
            protection_days: number;
            /**
             * Buffer Percentile
             * @default 90
             */
            buffer_percentile: number;
            /**
             * Fallback Buffer Days
             * @default 3
             */
            fallback_buffer_days: number;
            /**
             * Annual Holding Rate
             * @default 0.2
             */
            annual_holding_rate: number;
            /** Class Targets */
            class_targets?: {
                [key: string]: number;
            };
            /**
             * Funding Mode
             * @default funded
             * @enum {string}
             */
            funding_mode: "funded" | "unfunded_exploration";
        };
        /** Supplier */
        Supplier: {
            /** Supplier Id */
            supplier_id: string;
            /** Name */
            name: string;
            /** Minimum Order Value */
            minimum_order_value: number;
            /** Shared Daily Capacity */
            shared_daily_capacity?: number | null;
            /** Shared Capacity Unit */
            shared_capacity_unit?: ("base_units" | "volume") | null;
        };
        /** SupplierCapacity */
        SupplierCapacity: {
            /** Supplier Id */
            supplier_id: string;
            /** Sku */
            sku: string;
            /**
             * Dispatch Date
             * Format: date
             */
            dispatch_date: string;
            /** Available Units */
            available_units: number;
            /** Shared Limit Reference */
            shared_limit_reference?: string | null;
        };
        /** SupplierOffer */
        SupplierOffer: {
            /** Offer Id */
            offer_id: string;
            /** Supplier Id */
            supplier_id: string;
            /** Sku */
            sku: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date
             */
            valid_to: string;
            /** Price Per Base Unit */
            price_per_base_unit: number;
            /** Case Size */
            case_size: number;
            /** Moq Units */
            moq_units: number;
            /** Lead Time Days */
            lead_time_days: number;
            /** Dispatch Weekdays */
            dispatch_weekdays: number[];
            /** Order Weekdays */
            order_weekdays: number[];
            /** Deposit Fraction */
            deposit_fraction: number;
            /** Balance Days After Receipt */
            balance_days_after_receipt: number;
        };
        /** TransferLane */
        TransferLane: {
            /** Source */
            source: string;
            /** Destination */
            destination: string;
            /**
             * Transit Days
             * @enum {integer}
             */
            transit_days: 1 | 2;
            /** Dispatch Weekdays */
            dispatch_weekdays: number[];
            /** Capacity Units */
            capacity_units: number | null;
            /** Grouped Dispatch Fee */
            grouped_dispatch_fee: number;
            /** Pack Units */
            pack_units: number;
            /** Allowed Skus */
            allowed_skus: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindowRecord */
        WindowRecord: {
            /**
             * Origin
             * Format: date
             */
            origin: string;
            /** Horizon */
            horizon: number;
            /** Complete */
            complete: boolean;
            /** Valid Observations */
            valid_observations: number;
            /** Excluded By Reason */
            excluded_by_reason: {
                [key: string]: number;
            };
            /** Actual Units */
            actual_units: number;
            /** Forecast Units */
            forecast_units: number;
            /** Absolute Error */
            absolute_error: number;
            /** Signed Error */
            signed_error: number;
            /** Underforecast Units */
            underforecast_units: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    catalog_api_sample_get: {
        parameters: {
            query?: {
                size?: "fixture" | "full";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleCatalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_forecast_api_forecast_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    custom_forecast_api_forecast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResult"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
}
