import { type ForecastResult, displayedMaeImprovement, fixedNumber, methodNames, number, percent, shortDate, signedPercent } from './api';
import ForecastChart from './ForecastChart';
import Evaluation from './Evaluation';

export default function Demand({ result }: { result: ForecastResult }) {
  const selected = result.selection.find(r => r.method === result.selected_method)!;
  const m = selected.metrics.find(m => m.horizon === 28)!;
  const baselineRecord = result.selection.find(r => r.method === 'seasonal_naive')!;
  const baseline = baselineRecord.metrics.find(m => m.horizon === 28)!;
  const improvement = displayedMaeImprovement(baseline.mean_absolute_quantity_error, m.mean_absolute_quantity_error);
  return <div className="result-content" data-testid="forecast-result" data-run-id={result.run_id}>
    <section className="decision-banner"><div><span className={`status-tag ${result.status}`}>{result.status === 'evaluated' ? 'Historically evaluated' : result.status === 'provisional' ? 'Provisional forecast' : 'Incomplete forecast'}</span><h2>{methodNames[result.selected_method]}</h2><p>{result.selection_reason}</p></div><div className="as-of"><span>FORECAST FROM</span><strong>{shortDate(result.as_of)} {result.as_of.slice(0, 4)}</strong><small>{result.location_name} · {result.sku}</small></div></section>
    <div className="metric-grid"><Metric label="Next 28 days" value={number(result.visible_units)} unit="expected units" detail="Visible window"/><Metric label="Versus seasonal naive" value={percent(improvement, 0)} unit="lower quantity MAE" detail={`Baseline ${fixedNumber(baseline.mean_absolute_quantity_error)} → selected ${fixedNumber(m.mean_absolute_quantity_error)} units`}/><Metric label="Pooled signed bias" value={signedPercent(m.signed_bias_pct)} unit="pooled signed error" detail={`${number(m.signed_bias_units)} units · positive = overforecast`}/><Metric label="Evaluation coverage" value={`${m.valid_observations} / ${m.windows * 28}`} unit="scored daily observations" detail={`${m.complete_windows} complete windows · ${m.excluded_observations} excluded`}/></div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">{result.product_name} · {result.location_name}</p><h2>Sales and forecast</h2></div><span className="subtle-tag">56-day model horizon</span></div><ForecastChart result={result}/><div className="chart-note"><span><strong>Days 29–56 · provisional:</strong> {number(result.tail_units)} units.</span><span>Known events adjust the baseline once.</span></div>
      <details><summary>Daily quantities and history</summary><div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll daily-table"><table><thead><tr><th>Date</th><th>Ordinary baseline</th><th>Expected demand</th><th>Window</th><th>Event / fallback</th></tr></thead><tbody>{result.forecast.map(p => <tr key={p.day}><th scope="row">{p.day}</th><td>{number(p.baseline_units)}</td><td>{number(p.forecast_units)}</td><td>{p.provisional_tail ? 'Days 29–56 · provisional' : 'Days 1–28'}</td><td>{[p.reason, p.fallback].filter(Boolean).join(' · ') || 'Ordinary weekday'}</td></tr>)}</tbody></table></div><h3>Recent history</h3><div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll daily-table"><table><thead><tr><th>Date</th><th>Observed sales</th><th>Training estimate</th><th>Observation status</th></tr></thead><tbody>{result.history.map(p => <tr key={p.day}><th scope="row">{p.day}</th><td>{number(p.observed_sales)}</td><td>{number(p.training_estimate)}</td><td>{p.status.replaceAll('_', ' ')}</td></tr>)}</tbody></table></div></details>
    </section>
    <Evaluation result={result}/>
    <div className="two-column"><section className="panel"><p className="eyebrow">Protection period</p><h2>{number(result.buffer.units)} units <span className="heading-note">illustrative buffer</span></h2><p>{result.buffer.method === 'empirical_underforecast' ? `${result.buffer.percentile}th percentile of ${result.buffer.sample_count} complete ${result.buffer.protection_days}-day underforecast errors.` : `${result.buffer.fallback_days} days of forecast demand; only ${result.buffer.sample_count} complete protection-period windows.`}</p><p className="muted">{result.buffer.note}</p></section><section className="panel"><p className="eyebrow">Dataset</p><h2>Data quality</h2>{result.warnings.map(w => <p className="warning-line" key={w.code}><strong>{w.count} · {w.code.replaceAll('_', ' ')}</strong><span>{w.message}</span></p>)}<p className="footnote">Counts cover the dataset. Series-level exclusions are in the evaluation record.</p></section></div>
    <details className="metadata"><summary>Calculation record</summary><dl><dt>Run ID</dt><dd>{result.run_id}</dd><dt>Engine / schema</dt><dd>{result.engine_version} / {result.schema_version}</dd><dt>Input hash</dt><dd>{result.input_hash}</dd><dt>Engine calculation time</dt><dd>{number(result.elapsed_ms)} ms</dd></dl><p>Calculated on the server for this request. No stored result is substituted.</p></details>
  </div>;
}
function Metric({ label, value, unit, detail }: { label: string; value: string; unit: string; detail: string }) {
  return <section className="metric"><p>{label}</p><strong>{value}</strong><span>{unit}</span><small>{detail}</small></section>;
}
