import { useEffect, useRef, useState } from 'react';
import type { components } from './contracts.generated';
import ScenarioEvidence, { type EvidenceSelection } from './ScenarioEvidence';
import { scenarioApi, emptyScenario, type Baseline, type DetailRequest, type Detail } from './scenarioApi';
import { fixedNumber, number, percent, type Size } from './api';
import { evidenceTargetSummary, purchaseEvidenceTarget } from './evidenceTarget';
import LazyDetails, { MoreRows } from './LazyDetails';
import ReviewControls from './ReviewControls';
import type { ReviewMutationPhase, ReviewRecovery } from './reviewState';
import type { ReviewState } from './useReviewState';

type Plan = components['schemas']['PlanResult'];
const sar = (n: number | null) => n == null ? 'Unknown' : `SAR ${fixedNumber(n, 2)}`;

export default function PlanReview({onReady,onPlanInvalidated,onForecast,onScenarios,onReturnToOriginalScenario,reviewState,initialPlan,datasetLocked=false,recovery,scenarioDerived=false,mutationPhase,uploaded=false,onReviewed,onRecovery,onRecoveryClear,onMutation}:{onReady:(p:Plan,size:Size)=>void;onPlanInvalidated:(size:Size)=>void;onForecast:(d:Detail)=>void;onScenarios:(p:Plan,size:Size)=>void;onReturnToOriginalScenario:()=>void;reviewState:ReviewState;initialPlan?:Plan|null;datasetLocked?:boolean;recovery:ReviewRecovery|null;scenarioDerived?:boolean;mutationPhase:ReviewMutationPhase;uploaded?:boolean;onReviewed?:(p:Plan)=>void;onRecovery:(v:ReviewRecovery)=>void;onRecoveryClear:(reference:string)=>void;onMutation:(v:ReviewMutationPhase)=>void}) {
  const mutationPending=mutationPhase==='awaiting-response';
  const reviewGate=reviewState.gate;
  const reviewProtected=reviewState.protectedPlan;
  const [size, setSize] = useState<Size>(initialPlan?.provenance?.sample_size||'fixture');
  const [refresh, setRefresh] = useState(0);
  const [result, setResult] = useState<Plan | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(true);
  const [series, setSeries] = useState('');
  const [evidence,setEvidence]=useState<DetailRequest|EvidenceSelection|null>(null);
  const [captured,setCaptured]=useState<Baseline|null>(null);
  const [inspectRequest,setInspectRequest]=useState<{sku:string;loc:string;id?:string}|null>(null);
  const [inspectError,setInspectError]=useState('');
  const [purchaseLimit,setPurchaseLimit]=useState(12);
  const [movementLimit,setMovementLimit]=useState(20);
  const [serviceLimit,setServiceLimit]=useState(20);
  const initialConsumed=useRef(false);
  useEffect(()=>{if(!inspectRequest||!result?.proposed)return;const c=new AbortController();setInspectError('');
    if(result.review_id){setEvidence({expected_run_id:result.run_id,sku:inspectRequest.sku,location_id:inspectRequest.loc,action_id:inspectRequest.id});return()=>c.abort();}
    const load=captured?Promise.resolve(captured):scenarioApi<Baseline>('/api/scenarios/capture',c.signal,{size:uploaded?null:size,dataset_hash:result.input_hash,purchases:result.proposed.purchases,movements:result.proposed.movements});
    load.then(b=>{if(!c.signal.aborted){setCaptured(b);setEvidence({baseline:b.baseline,scenario:emptyScenario(),policy:'original',sku:inspectRequest.sku,location_id:inspectRequest.loc,action_id:inspectRequest.id,expected_action_hash:b.original.action_hash});}}).catch(e=>{if(!c.signal.aborted)setInspectError(e.message);});return()=>c.abort();
  },[inspectRequest,result,size,uploaded]);
  useEffect(() => {
    if(initialPlan&&refresh===0&&!initialConsumed.current){initialConsumed.current=true;setResult(initialPlan);setSeries(initialPlan.forecasts[0]?`${initialPlan.forecasts[0].sku}/${initialPlan.forecasts[0].location_id}`:'');setBusy(false);onReady(initialPlan,size);return;}
    const controller = new AbortController();
    setResult(null); setError(null); setBusy(true); setSeries('');setEvidence(null);setCaptured(null);setInspectRequest(null);
    scenarioApi<Plan>('/api/plan/sample', controller.signal, { size })
      .then(next => { if (!controller.signal.aborted) { setResult(next); onReady(next,size); setSeries(next.forecasts[0] ? `${next.forecasts[0].sku}/${next.forecasts[0].location_id}` : ''); } })
      .catch((e: Error) => { if (!controller.signal.aborted) setError(e.message); })
      .finally(() => { if (!controller.signal.aborted) setBusy(false); });
    return () => controller.abort();
  }, [size, refresh]);
  useEffect(()=>{setPurchaseLimit(12);setMovementLimit(20);setServiceLimit(20);},[result?.run_id]);
  const proposed = result?.proposed;
  const valid = proposed?.replay.feasible && (result?.status === 'feasible' || result?.status === 'feasible_fallback');
  const s = proposed?.replay.summary;
  const benchmarkFallback = !!result?.stages.some(stage=>stage.name==='independent_fallback'&&stage.status==='benchmark');
  const policyRows = result && proposed ? [proposed,...(!benchmarkFallback&&result.benchmark?[result.benchmark]:[]),result.no_action].filter(x=>x!=null) : [];
  const serviceRows = proposed ? [...proposed.replay.service].sort((a,b)=>
    (b.unmet-a.unmet)||(b.tail_unmet-a.tail_unmet)||Number(b.must_stock)-Number(a.must_stock)||a.sku.localeCompare(b.sku)||a.location_id.localeCompare(b.location_id)
  ) : [];

  const actionWindow = (day: string) => {
    const offset = (Date.parse(day) - Date.parse(result!.as_of)) / 86_400_000;
    return offset < 7 ? 'Release candidate' : offset < 28 ? 'Planned' : 'Provisional tail';
  };
  const [sku, loc] = series.split('/');
  return <>
    <section className="filters" aria-label="Planning controls"><label>Planning dataset<select value={size} disabled={busy||uploaded||datasetLocked||mutationPending} onChange={e => {if(!mutationPending){const next=e.target.value as Size;onPlanInvalidated(next);setSize(next);}}}><option value="fixture">{result?.provenance?.source==='portable'?'Reopened portable snapshot':uploaded?'Validated uploaded workbook':'Small fixture · 10 SKUs'}</option><option value="full">Full sample · 60 SKUs</option></select></label>
      <button className="primary-button" disabled={busy||reviewProtected||mutationPending} onClick={() => {if(!mutationPending){onPlanInvalidated(size);setRefresh(v => v + 1);}}}>{busy ? 'Calculating plan…' : 'Recalculate plan'}</button>{reviewProtected&&<p>Use reviewed regeneration or explicitly create a new draft below.</p>}</section>
    <div role="status" aria-live="polite">{busy && <div className="loading"><span className="spinner"/>Evaluating network demand, purchasing, allocation and dated payments…</div>}</div>
    {error && <div role="alert" className="error"><strong>Plan unavailable</strong><p>{error}</p><button disabled={mutationPending} onClick={() => {if(!mutationPending)setRefresh(v => v + 1);}}>Retry plan</button></div>}
    {result && !busy && <div className="result-content" data-testid="plan-result" data-run-id={result.run_id}>
      <section className="decision-banner"><div><span className="status-tag">{!valid ? 'Not executable' : reviewGate.blocked ? 'Unresolved — current result required' : 'Independently checked'}</span><h2>{!valid ? 'Resolve planning failures before using recommendations' : reviewGate.blocked ? 'Previous calculation — review changes are not applied' : proposed?.name || 'Validated constrained plan'}</h2>
        <p>{result.status === 'feasible_fallback' && proposed?.name === 'Validated constrained plan' ? `The deterministic constrained planner passed independent stock and funding replay. No optimality${benchmarkFallback?' or improvement over the identical constrained benchmark':''} is claimed; detailed stages remain in calculation evidence.` : valid ? 'Daily stock and dated funding checks passed. Uncovered demand remains visible below.' : 'Incomplete inputs or a hard constraint failure prevents a funded plan.'}</p></div>
        <div className="as-of"><span>PLAN FROM</span><strong>{result.as_of}</strong><small>28-day review · 56-day model</small></div></section>
      {result.failures.length > 0 && <section className="panel error" role="alert"><h2>Planning failures</h2>{result.failures.map((f, i) => <p key={i}><strong>{f.code}</strong> · {[f.sku, f.location_id, f.supplier_id, f.day].filter(Boolean).join(' / ')} · {f.message}</p>)}</section>}
      <p className="dataset-context">{result.provenance?.source==='portable'?'Portable snapshot source':uploaded?'Uploaded workbook':result.provenance?.sample_size==='full'?'Bundled full sample':'Bundled fixture'} · {result.dataset_id} · planning date {result.as_of}. Proposed actions are not placed orders.</p>
      {(result.review_id||recovery)&&<ReviewControls recovery={recovery} reviewState={reviewState} mutationPhase={mutationPhase} onRecovery={onRecovery} onRecoveryClear={onRecoveryClear} onMutation={onMutation} plan={result} onPlan={next=>{setResult(next);setEvidence(null);setCaptured(null);setInspectRequest(null);onReady(next,size);onReviewed?.(next);}}/>}
      {valid && proposed && s && <>
        {scenarioDerived?<p className="notice">This reviewed plan already includes scenario assumptions. The current baseline-capture contract cannot preserve those assumptions as a new baseline without dropping or applying them twice. <button disabled={mutationPending} onClick={()=>{if(!mutationPending)onReturnToOriginalScenario();}}>Return to original scenario baseline</button></p>:<><button className="primary-button" disabled={reviewGate.blocked||mutationPending} onClick={()=>{if(!mutationPending)onScenarios(result,size);}}>Test disruptions with this baseline</button>{(reviewGate.blocked||mutationPending)&&<p className="notice">{mutationPending?'The review mutation is still being saved.':reviewGate.reason} Scenario handoff remains blocked.</p>}</>}
        {inspectRequest&&!evidence&&!inspectError&&<p role="status">Preparing action evidence…</p>}{inspectError&&<p role="alert">{inspectError}</p>}
        {evidence&&<ScenarioEvidence request={evidence} reviewReference={result.review_id} navigationLocked={mutationPending} onForecast={onForecast} onClose={()=>{setEvidence(null);setInspectRequest(null);}}/>}
        <div className="metric-grid"><section className="metric"><p>New purchase commitment</p><strong data-testid="plan-commitment">{sar(s.commitments)}</strong><small>{sar(s.visible_commitments)} visible · {sar(s.tail_commitments)} provisional tail</small></section>
          <section className="metric"><p>Scheduled payments</p><strong data-testid="plan-payments">{sar(s.payments)}</strong><small>Existing obligations + new purchases + movement fees</small></section>
          <section className="metric"><p>Projected unit fill · 28 days</p><strong>{percent(s.fill_pct)}</strong><small>{number(s.fulfilled)} of {number(s.demand)} expected units · not guaranteed service</small></section>
          <section className="metric"><p>Uncovered demand · 28 days</p><strong>{number(s.unmet)}</strong><small>{number(s.tail_unmet)} more units in provisional days 29–56</small></section></div>
        <section className="panel"><h2>Compare on the same demand and limits</h2><p>Day-56 excess is above next-seven-day coverage plus store buffers, repeating the final forecast week; DC stock covers only net store requirements. Inventory value includes on-hand and in-transit stock at acquisition cost. Revenue exposure is modeled unmet units × assumed net selling price, not proven lost revenue.</p>{benchmarkFallback&&<p>The proposed plan is the constrained benchmark, so it appears once.</p>}<div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll"><table><thead><tr><th>Policy</th><th>Projected unit fill</th><th>Unmet units</th><th>Commitments · SAR</th><th>Movement fees · SAR</th><th>Day-56 inventory value · SAR</th><th>Day-56 excess · units</th><th>Weekly buffer deficits · units</th><th>Revenue exposure · SAR</th></tr></thead><tbody>{policyRows.map(p => <tr key={p.name}><th>{p.name}{!p.replay.feasible && ' · invalid'}</th><td>{percent(p.replay.summary.fill_pct)}</td><td>{number(p.replay.summary.unmet)}</td><td>{fixedNumber(p.replay.summary.commitments,2)}</td><td>{fixedNumber(p.replay.summary.movement_expense,2)}</td><td>{fixedNumber(p.replay.summary.ending_inventory_investment,2)}</td><td>{number(p.replay.summary.terminal_excess_units)}</td><td>{number(p.replay.summary.weekly_buffer_deficit)}</td><td>{fixedNumber(p.replay.summary.revenue_exposure,2)}</td></tr>)}</tbody></table></div></section>
        <section className="panel"><h2>What to buy</h2><p>Only orders in the next seven days are release candidates. Later orders remain planned; arrivals must occur within day 56.</p>
          {proposed.purchases.length === 0 ? <p>No feasible new purchase is recommended.</p> : <><div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll daily-table"><table data-testid="purchase-table"><thead><tr><th>SKU / supplier</th><th>Units</th><th>Order</th><th>Dispatch</th><th>DC receipt</th><th>Value · SAR</th><th>Evidence</th></tr></thead><tbody>{proposed.purchases.slice(0,purchaseLimit).map(p => <tr key={p.action_id}><th>{p.sku}<small> · {p.supplier_id}</small></th><td>{p.units}</td><td>{p.order_date}<small> · {actionWindow(p.order_date)}</small></td><td>{p.dispatch_date}</td><td>{p.arrival_date}</td><td>{fixedNumber(p.value,2)}</td><td><LazyDetails summary="Dates, payments and forecast"><p>{p.reason}</p><p>{p.action_id} · {p.supplier_id} → {p.destination} · offer {p.offer_id}</p><p>{evidenceTargetSummary(purchaseEvidenceTarget(proposed,p.action_id))}</p><button data-evidence-location={purchaseEvidenceTarget(proposed,p.action_id)?.location_id||'unavailable'} disabled={!purchaseEvidenceTarget(proposed,p.action_id)?.location_id} onClick={()=>{const target=purchaseEvidenceTarget(proposed,p.action_id);if(target?.location_id){setEvidence(null);setInspectRequest({sku:p.sku,loc:target.location_id,id:p.action_id});}}}>Inspect purchase and forecast</button>{proposed.replay.payments.filter(x => x.reference === p.action_id).map(x => <p key={x.kind}>{x.kind} · {x.due_date} · {sar(x.amount)}</p>)}<p>Forecasts: {result.forecasts.filter(x => x.sku === p.sku).map(x => `${x.location_id}: ${x.run_id}`).join('; ')}</p></LazyDetails></td></tr>)}</tbody></table></div><MoreRows count={proposed.purchases.length} shown={Math.min(purchaseLimit,proposed.purchases.length)} label="purchase actions" onMore={()=>setPurchaseLimit(value=>Math.min(value+12,proposed.purchases.length))} onAll={()=>setPurchaseLimit(proposed.purchases.length)}/></>}
        </section>
        <section className="panel"><h2>Where stock goes</h2><p>Shared stock is allocated after local demand. Receivers can use it only on the arrival date. Donor stores keep their dated reserve.</p>
          {proposed.movements.length === 0 ? <p>No feasible movement is recommended.</p> : <><div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll daily-table"><table data-testid="movement-table"><thead><tr><th>SKU</th><th>From → to</th><th>Units</th><th>Dispatch</th><th>Arrival</th><th>Evidence</th></tr></thead><tbody>{proposed.movements.slice(0,movementLimit).map(m => <tr key={m.action_id}><th>{m.sku}</th><td>{m.source} → {m.destination}</td><td>{m.units}</td><td>{m.dispatch_date}<small> · {actionWindow(m.dispatch_date)}</small></td><td>{m.arrival_date}</td><td><LazyDetails summary="Stock and dependencies"><p>{m.reason}</p><button onClick={()=>{setEvidence(null);setInspectRequest({sku:m.sku,loc:m.destination,id:m.action_id});}}>Inspect movement and forecast</button><p>Supply pool before dispatch: opening stock, confirmed receipts and these dated purchases: {proposed.purchases.filter(p => p.sku === m.sku && p.arrival_date <= m.dispatch_date).map(p => p.action_id).join(', ') || 'none'}.</p><p>All movement dependencies were checked together by stock replay; stock is fungible within a location.</p></LazyDetails></td></tr>)}</tbody></table></div><MoreRows count={proposed.movements.length} shown={Math.min(movementLimit,proposed.movements.length)} label="movement actions" onMore={()=>setMovementLimit(value=>Math.min(value+20,proposed.movements.length))} onAll={()=>setMovementLimit(proposed.movements.length)}/></>}
        </section>
        <section className="panel"><h2>Payment capacity through {result.payment_through}</h2><p>Purchasing outflows and transfer fees, in SAR. New purchase value consumes commitment authority on the order date; deposits and balances consume payment ceilings on their due dates. Transfer fees also use their separate transfer allowance. Headroom is a declared allowance, not a bank balance. {sar(s.later_payments)} is due beyond the visible window.</p><div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll"><table data-testid="cash-table"><thead><tr><th>Week from</th><th>New commitments</th><th>Commitment authority left</th><th>Existing payments</th><th>New payments</th><th>Total payments</th><th>Payment ceiling</th><th>Payment headroom</th><th>Movement fees / allowance</th></tr></thead><tbody>{proposed.replay.cash.map(w => <tr key={w.week_start}><th>{w.week_start}</th><td>{fixedNumber(w.commitments,2)}</td><td>{fixedNumber(w.commitment_headroom,2)}</td><td>{fixedNumber(w.existing_payments,2)}</td><td>{fixedNumber(w.new_payments,2)}</td><td>{fixedNumber(w.total_payments,2)}</td><td>{fixedNumber(w.payment_ceiling,2)}</td><td>{fixedNumber(w.payment_headroom,2)}</td><td>{fixedNumber(w.movement_fees,2)} / {fixedNumber(w.transfer_budget,2)}</td></tr>)}</tbody></table></div></section>
        <LazyDetails className="panel" summary="Service targets by class and store"><p>Target shortfall is measured from pooled units within each priority group. This is the solver's service objective; individual SKU shortages remain below.</p><div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll daily-table"><table><thead><tr><th>Store / priority</th><th>Window</th><th>Expected / fulfilled units</th><th>Target</th><th>Target shortfall · units</th></tr></thead><tbody>{proposed.replay.service_groups.map(g => <tr key={`${g.location_id}/${g.service_class}/${g.must_stock}/${g.window}`}><th>{g.location_id} · {g.must_stock ? 'Must-stock · ' : ''}{g.service_class}</th><td>{g.window}</td><td>{number(g.demand)} / {number(g.fulfilled)}</td><td>{percent(g.target*100,0)}</td><td>{number(g.target_shortfall)}</td></tr>)}</tbody></table></div></LazyDetails>
        <LazyDetails className="panel" summary={`Planner diagnostic traces · ${result.exceptions.length}`}><p>These are rejected-path and solver traces for advanced review. They are not automatically causes of a final-plan shortage.</p>{result.exceptions.map((x,i) => <p key={i}><strong>{x.code}</strong> · {[x.sku,x.location_id,x.supplier_id,x.day].filter(Boolean).join(' / ')} · {x.message}</p>)}</LazyDetails>
        <section className="panel"><h2>Service and shortages</h2><p>Largest visible shortages appear first, followed by provisional-tail shortages and fully covered series. Need is the 56-day forecast plus buffer minus initial usable stock and confirmed receipts. All {serviceRows.length} series remain available below.</p><div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll daily-table"><table data-testid="service-table"><thead><tr><th>SKU / store</th><th>Priority / target</th><th>Unconstrained need</th><th>28-day fulfilled / demand</th><th>Visible unmet</th><th>Tail unmet</th><th>Reason</th></tr></thead><tbody>{serviceRows.slice(0,serviceLimit).map(x => <tr key={`${x.sku}/${x.location_id}`}><th>{x.sku} / {x.location_id}</th><td>{x.must_stock ? 'Must-stock · ' : ''}{x.service_class} / {percent(100*x.target,0)}</td><td>{number(x.unconstrained_need)}</td><td>{number(x.fulfilled)} / {number(x.demand)}</td><td>{number(x.unmet)}</td><td>{number(x.tail_unmet)}</td><td>{x.reason_summary ? <LazyDetails summary={x.reason_summary}>{x.shortage_evidence.map((e,i)=><p key={`${e.window}/${e.start_date}/${i}`}><strong>{e.window==='visible'?'Visible days 1–28':'Provisional tail days 29–56'} · {number(e.quantity)} units · {e.status==='established_limit'?'Established within the stated single-path checks':'Attribution limited'}</strong><br/>{e.detail}<br/><small>{e.reason_codes.join(' · ')}</small></p>)}</LazyDetails> : 'Covered'}</td></tr>)}</tbody></table></div><MoreRows count={serviceRows.length} shown={Math.min(serviceLimit,serviceRows.length)} label="SKU-store series" onMore={()=>setServiceLimit(value=>Math.min(value+20,serviceRows.length))} onAll={()=>setServiceLimit(serviceRows.length)}/></section>
        <LazyDetails className="panel" summary="Daily inventory, forecasts and calculation evidence"><label>Inventory series<select value={series} onChange={e => setSeries(e.target.value)}>{result.forecasts.map(f => <option key={`${f.sku}/${f.location_id}`}>{f.sku}/{f.location_id}</option>)}</select></label><button disabled={!sku||!loc} onClick={()=>{setEvidence(null);setInspectRequest({sku,loc});}}>Review selected series forecast</button><p>Open the selected evidence to load its independently replayed daily stock ledger, including related donor and receiver locations.</p>
          {result.forecasts.filter(f => f.sku === sku && f.location_id === loc).map(f => <p key={f.run_id}>{f.method} · {f.status} · buffer {number(f.buffer.units)} units, {f.buffer.protection_days} days, {f.buffer.sample_count} complete windows · forecast run {f.run_id}</p>)}
          <p>Plan run {result.run_id} · {result.engine_version} · {number(result.elapsed_ms)} ms</p><p>Input hash: {result.input_hash}</p><h3>Solver stages</h3>{result.stages.map((stage,i) => <p key={i}>{stage.name} · {stage.status} · {number(stage.elapsed_ms)} ms · gap {stage.gap == null ? 'unavailable' : percent(100*stage.gap)}</p>)}<h3>Policy assumptions</h3>{result.assumptions.map(a => <p key={a}>{a}</p>)}
        </LazyDetails>
      </>}
      {result.issues.length > 0 && <details className="panel"><summary>Input quality warnings and validation</summary>{result.issues.map((i,n) => <p key={n}>{i.severity} · {i.code} · {i.count}: {i.message}</p>)}</details>}
    </div>}
  </>;
}
