import { useEffect, useRef, useState } from 'react';
import { number, fixedNumber, percent, type Size } from './api';
import { scenarioApi, emptyScenario, type Baseline, type Definition, type Comparison, type Outcome, type Detail, type DetailRequest, type Plan } from './scenarioApi';
import ScenarioEvidence from './ScenarioEvidence';
import { evidenceTargetSummary, purchaseEvidenceTarget } from './evidenceTarget';
const plus=(day:string,n:number)=>new Date(Date.parse(day)+n*86400000).toISOString().slice(0,10);

export default function Scenarios({initial,onForecast,onReview,uploaded=false,firstSku='SKU001',firstStore='S1'}:{uploaded?:boolean;firstSku?:string;firstStore?:string;initial?:{plan:Plan;size:Size}|null;onForecast:(d:Detail)=>void;onReview?:(p:Plan)=>void}) {
  const initialSize=initial?.plan.provenance?.sample_size||initial?.size||'fixture';
  const [size,setSize]=useState<Size>(initialSize);const [base,setBase]=useState<Baseline|null>(null);
  const [draft,setDraft]=useState<Definition>(emptyScenario);const [result,setResult]=useState<Comparison|null>(null);
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [edited,setEdited]=useState(false);const [retry,setRetry]=useState(0);
  const [evidence,setEvidence]=useState<DetailRequest|null>(null);const active=useRef<AbortController|null>(null);
  const stop=()=>{active.current?.abort();setBusy(false);setEvidence(null);};
  useEffect(()=>{const c=new AbortController();active.current?.abort();active.current=c;setBusy(true);setError('');setBase(null);setResult(null);setDraft(emptyScenario());setEdited(false);setEvidence(null);
    const captured=initialSize===size&&initial?.plan.proposed?.replay.feasible&&initial.plan.input_hash===initial.plan.provenance?.dataset_hash;
    if(initial&&!captured){setBusy(false);setError('This plan cannot be captured as a new baseline because its assumptions or independent result are not the original current dataset. Return to the original baseline first.');return()=>c.abort();}
    const body=captured?{size:initial!.plan.provenance?.sample_size??null,dataset_hash:initial!.plan.input_hash,purchases:initial!.plan.proposed!.purchases,movements:initial!.plan.proposed!.movements}:{size};
    scenarioApi<Baseline>(captured?'/api/scenarios/capture':'/api/scenarios/baseline',c.signal,body).then(b=>{if(!c.signal.aborted)setBase(b);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});
    return ()=>c.abort();
  },[size,retry,initial,uploaded]);
  useEffect(()=>()=>active.current?.abort(),[]);
  const edit=(d:Definition)=>{stop();setDraft(d);setResult(null);setError('');setEdited(true);};
  const start=base?.as_of||'';const end=start?plus(start,55):'';
  const preset=(name:string)=>{if(!base)return;
    if(name==='Promotion')edit({...draft,uplifts:[{scope:'sku',scope_id:firstSku,start,end:plus(start,13),percent:30}]});
    if(name==='Supplier disruption'){const supplier=base.supplier_options.find(s=>s.existing_order_ids.length>0&&s.future_paths);if(!supplier){setError('No single supplier supports both an existing-receipt delay and a future availability change in this dataset. Configure one coherent supplier manually.');return;}edit({...draft,delays:[{supplier_id:supplier.supplier_id,days:3,existing_order_ids:supplier.existing_order_ids.slice(0,1),future_paths:false}],availability:[{supplier_id:supplier.supplier_id,start,end,remaining_fraction:0}]});}
    if(name==='Tighter funds')edit({...draft,funding:base.weeks.map(w=>({...w,commitment:0,payment:w.payment}))});
  };
  const run=async()=>{if(!base)return;stop();const c=new AbortController();active.current=c;setBusy(true);setError('');setResult(null);
    try{const r=await scenarioApi<Comparison>('/api/scenarios/compare',c.signal,{baseline:base.baseline,scenario:draft});if(!c.signal.aborted){setResult(r);setEdited(false);}}
    catch(e){if(!c.signal.aborted)setError((e as Error).message);}finally{if(!c.signal.aborted)setBusy(false);}
  };
  const reviewReplan=async()=>{if(!base||!result)return;stop();const c=new AbortController();active.current=c;setBusy(true);try{const p=await scenarioApi<Plan>('/api/workflow/scenario',c.signal,{baseline:base.baseline,scenario:result.definition});if(!c.signal.aborted)onReview?.(p);}catch(e){if(!c.signal.aborted)setError((e as Error).message);}finally{if(!c.signal.aborted)setBusy(false);}};
  const inspect=(o:Outcome,sku:string,loc:string,action_id?:string)=>{if(!base)return;setEvidence({baseline:base.baseline,scenario:result?.definition||emptyScenario(),policy:o.policy,actions:{purchases:o.purchases,movements:o.movements},expected_action_hash:o.action_hash,expected_scenario_hash:result?.scenario_hash,sku,location_id:loc,action_id});};
  const update=<K extends keyof Definition>(field:K,index:number,patch:Partial<NonNullable<Definition[K]>[number]>)=>edit({...draft,[field]:(draft[field]||[]).map((r,i)=>i===index?{...r,...patch}:r)});
  const remove=(field:keyof Definition,index:number)=>edit({...draft,[field]:(draft[field]||[]).filter((_,i)=>i!==index)});
  const supplierLabel=(id:string)=>{const supplier=base?.supplier_options.find(s=>s.supplier_id===id);return supplier?`${supplier.supplier_id} · ${supplier.name}`:id;};
  const delays=draft.delays||[];const availability=draft.availability||[];
  const coherentSupplier=delays.length===1&&availability.length===1&&delays[0].supplier_id===availability[0].supplier_id?delays[0].supplier_id:null;
  return <>
    <section className="filters"><label>Scenario dataset<select disabled={uploaded} value={uploaded?'uploaded':size} onChange={e=>{stop();setBase(null);setResult(null);setSize(e.target.value as Size);}}>{uploaded?<option value="uploaded">{base?.baseline.provenance?.source==='portable'?'Portable snapshot':'Uploaded dataset'}</option>:<><option value="fixture">Small fixture · 10 SKUs</option><option value="full">Full sample · 60 SKUs</option></>}</select></label><button onClick={()=>{stop();setDraft(emptyScenario());setResult(null);setEdited(false);setError('');}} disabled={!base}>Reset to baseline</button></section>
    {busy&&<p className="loading" role="status">{base?'Evaluating frozen actions and calculating a new constrained plan…':'Loading immutable sample baseline…'}</p>}
    {error&&<div className="error" role="alert">{error} <button onClick={()=>base?run():setRetry(v=>v+1)}>Retry scenario</button></div>}
    {base&&<><p className="notice">Baseline: {base.baseline.provenance?.source.replaceAll('_',' ')} · {base.baseline.provenance?.dataset_id} · planning date {base.as_of}. Original action snapshot retained. Each run starts from this baseline. Drafts are local to this tab; no orders are sent.</p>{result?.replanned.feasible&&onReview&&<button disabled={busy} onClick={reviewReplan}>Review replanned actions</button>}
      <section className="panel"><span className="scenario-icon" aria-hidden="true"><svg viewBox="0 0 24 24" width="28" height="28"><path d="M5 4v4c0 2.2 1.8 4 4 4h9m0 0-3-3m3 3-3 3M5 20v-4c0-2.2 1.8-4 4-4" fill="none" stroke="currentColor"/></svg></span><h2>Changes to test</h2><p>Presets populate editable controls and can be combined. Overlapping changes to the same SKU/store/day or supplier/date are rejected.</p><div className="scenario-buttons">{['Promotion','Supplier disruption','Tighter funds'].map(n=><button key={n} onClick={()=>preset(n)}>{n}</button>)}</div>
      <h3>Dated demand uplift</h3>{(draft.uplifts||[]).map((u,i)=><div className="scenario-controls" key={i}><label>Uplift scope<select value={u.scope} onChange={e=>update('uplifts',i,{scope:e.target.value as typeof u.scope,scope_id:e.target.value==='store'?firstStore:e.target.value==='category'?base.categories[0]:firstSku})}><option value="sku">SKU</option><option value="category">Category</option><option value="store">Store</option></select></label><label>Scope identifier<input value={u.scope_id} onChange={e=>update('uplifts',i,{scope_id:e.target.value})}/></label><label>Uplift percent<input type="number" min="0" max="500" value={u.percent} onChange={e=>update('uplifts',i,{percent:Number(e.target.value)})}/></label><label>Demand from<input type="date" value={u.start} onChange={e=>update('uplifts',i,{start:e.target.value})}/></label><label>Demand through<input type="date" value={u.end} onChange={e=>update('uplifts',i,{end:e.target.value})}/></label><button onClick={()=>remove('uplifts',i)}>Remove uplift</button></div>)}<button onClick={()=>edit({...draft,uplifts:[...(draft.uplifts||[]),{scope:'sku',scope_id:firstSku,start,end:plus(start,13),percent:20}]})}>Add uplift</button>
      <h3>Supplier receipt delay</h3><p>Selected existing receipts move later to an open receiving day. Future paths apply to all new orders in the 56-day horizon; lead times above 14 days are unsupported. Existing fixed payables never move.</p>{(draft.delays||[]).map((d,i)=><div className="scenario-controls" key={i}><label>Delayed supplier<select value={d.supplier_id} onChange={e=>update('delays',i,{supplier_id:e.target.value,existing_order_ids:[]})}>{base.suppliers.map(s=><option key={s} value={s}>{supplierLabel(s)}</option>)}</select></label><label>Delay days<input type="number" min="1" max="14" value={d.days} onChange={e=>update('delays',i,{days:Number(e.target.value)})}/></label><label><input type="checkbox" checked={d.future_paths} onChange={e=>update('delays',i,{future_paths:e.target.checked})}/>Future purchasing paths</label>{base.existing_orders.filter(o=>o.supplier===d.supplier_id).map(o=><label key={o.id}><input type="checkbox" checked={d.existing_order_ids?.includes(o.id)} onChange={e=>update('delays',i,{existing_order_ids:e.target.checked?[...(d.existing_order_ids||[]),o.id]:(d.existing_order_ids||[]).filter(x=>x!==o.id)})}/>{o.id} · original receipt {o.arrival}</label>)}<button onClick={()=>remove('delays',i)}>Remove delay</button></div>)}<button onClick={()=>edit({...draft,delays:[...(draft.delays||[]),{supplier_id:base.suppliers[0],days:1,existing_order_ids:[],future_paths:true}]})}>Add delay</button>
      <h3>Remaining supplier availability</h3><p>New purchasing only, by dispatch date. Confirmed inbound and shared supplier ceilings are unchanged.</p>{(draft.availability||[]).map((a,i)=><div className="scenario-controls" key={i}><label>Capacity supplier<select value={a.supplier_id} onChange={e=>update('availability',i,{supplier_id:e.target.value})}>{base.suppliers.map(s=><option key={s} value={s}>{supplierLabel(s)}</option>)}</select></label><label>Remaining percent<input type="number" min="0" max="100" value={a.remaining_fraction*100} onChange={e=>update('availability',i,{remaining_fraction:Number(e.target.value)/100})}/></label><label>Dispatch from<input type="date" value={a.start} onChange={e=>update('availability',i,{start:e.target.value})}/></label><label>Dispatch through<input type="date" value={a.end} onChange={e=>update('availability',i,{end:e.target.value})}/></label><button onClick={()=>remove('availability',i)}>Remove availability</button></div>)}<button onClick={()=>edit({...draft,availability:[...(draft.availability||[]),{supplier_id:base.suppliers[0],start,end,remaining_fraction:.5}]})}>Add availability reduction</button>
      <h3>Weekly funding · SAR</h3><p>New commitment limits authorize purchase value; payment ceilings limit cash due that week. Both use SAR. Leave a field blank to keep its baseline value. Payments include fixed existing obligations.</p>{(draft.funding||[]).map((f,i)=><div className="scenario-controls" key={i}><label>Funding week<select value={f.week_start} onChange={e=>update('funding',i,{week_start:e.target.value})}>{base.weeks.map(w=><option key={w.week_start}>{w.week_start}</option>)}</select></label><label>New commitment limit<input type="number" min="0" step=".01" value={f.commitment??''} onChange={e=>update('funding',i,{commitment:e.target.value===''?null:Number(e.target.value)})}/></label><label>Payment ceiling<input type="number" min="0" step=".01" value={f.payment??''} onChange={e=>update('funding',i,{payment:e.target.value===''?null:Number(e.target.value)})}/></label><button onClick={()=>remove('funding',i)}>Remove funding change</button></div>)}<button onClick={()=>edit({...draft,funding:[...(draft.funding||[]),{...base.weeks[0]}]})}>Add funding week</button>
      <h3>Draft change summary</h3>{coherentSupplier&&<p data-testid="supplier-preset-summary">Supplier disruption · {supplierLabel(coherentSupplier)} · existing receipt delay and dated availability use this supplier.</p>}<ul>{(draft.uplifts||[]).map((u,i)=><li key={`u${i}`}>{u.scope} {u.scope_id}: +{u.percent}% from {u.start} to {u.end}</li>)}{(draft.delays||[]).map((d,i)=><li key={`d${i}`}>{supplierLabel(d.supplier_id)}: +{d.days} days · existing {d.existing_order_ids?.join(', ')||'none'} · future paths {d.future_paths?'yes':'no'}</li>)}{(draft.availability||[]).map((a,i)=><li key={`a${i}`}>{supplierLabel(a.supplier_id)}: {a.remaining_fraction*100}% remaining · {a.start}–{a.end}</li>)}{(draft.funding||[]).map((f,i)=><li key={`f${i}`}>{f.week_start}: commitment {f.commitment??'unchanged'} / payment {f.payment??'unchanged'} SAR</li>)}</ul>
      {edited&&<p role="status" className="notice">Controls changed — run this draft to see current scenario results. Previous comparisons are hidden.</p>}<button className="primary-button" disabled={busy} onClick={run}>Run scenario live</button></section>
      {!result&&!edited&&!busy&&<p className="notice">Original baseline restored. No scenario changes are applied.</p>}
      <section className="panel" data-testid="scenario-results" data-scenario-hash={result?.scenario_hash||'baseline'}><h2>{result?'Original, frozen and replanned':'Original baseline'}</h2><p>Original uses the baseline assumptions. Frozen keeps those actions under your changes; replanned calculates new actions under the same changes. Comparisons are estimates, not guaranteed savings.</p><p>{result?.note||'Validated original actions under original assumptions.'}</p>
        <div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll"><table><thead><tr><th>Policy / status</th><th>28-day fill</th><th>Unmet / tail unmet</th><th>Commitments · SAR</th><th>Payments · SAR</th><th>Day-56 inventory value · SAR</th><th>Movement expense · SAR</th></tr></thead><tbody>{(result?[result.original,result.frozen,result.replanned]:[base.original]).map(o=><tr key={o.policy}><th>{o.policy} · {o.status==='feasible_fallback'?'Validated constrained plan':o.feasible?'Independently checked':'Infeasible'}</th><td>{percent(o.summary?.fill_pct)}</td><td>{number(o.summary?.unmet)} / {number(o.summary?.tail_unmet)}</td><td>{fixedNumber(o.summary?.commitments,2)}</td><td>{fixedNumber(o.summary?.payments,2)}</td><td>{fixedNumber(o.summary?.ending_inventory_investment,2)}</td><td>{fixedNumber(o.summary?.movement_expense,2)}</td></tr>)}</tbody></table></div>
        {(result?[result.original,result.frozen,result.replanned]:[base.original]).some(o=>o.status==='feasible_fallback')&&<p>The joint optimizer did not complete within the live calculation budget. Validated constrained plans passed independent feasibility checks; they may still have shortages and are not globally optimal.</p>}{result&&<><p>Invalid frozen policies have unavailable outcome metrics and deltas; cash below shows attempted obligations.</p><div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll"><table><thead><tr><th>Delta · later minus earlier</th><th>Shock: frozen − original</th><th>Replanning: replanned − frozen</th></tr></thead><tbody>{Object.keys(result.shock_delta).map(k=><tr key={k}><th>{k.replaceAll('_',' ')}{k==='fill_pct'?' · percentage points':''}</th><td>{number(result.shock_delta[k])}</td><td>{number(result.replan_delta[k])}</td></tr>)}</tbody></table></div><details><summary>Normalized changes and scenario version</summary>{result.changes.map((c,i)=><p key={i}>{c}</p>)}<p>{result.scenario_hash}</p></details><details><summary>Added, removed and changed actions · {result.action_changes.length}</summary>{result.action_changes.map((a,i)=><p key={i}>{a.change} {a.kind} · {a.business_key} · {a.before?.units??'none'} → {a.after?.units??'none'} units · receipt {a.before?.arrival_date??'none'} → {a.after?.arrival_date??'none'}</p>)}</details></>}
        {(result?[result.original,result.frozen,result.replanned]:[base.original]).map(o=><section key={o.policy}><h3>{o.policy} evidence</h3>{o.failures.length>0&&<details open><summary>Hard-constraint failures · {o.failures.length}</summary>{o.failures.map((f,i)=><p key={i} className="error">{f.code} · {f.sku} {f.day} · {f.message}</p>)}</details>}
          <details><summary>Weekly payments and headroom · {o.policy}</summary>{o.cash.map(w=><p key={w.week_start}>{w.week_start} · commitments {fixedNumber(w.commitments,2)} / headroom {fixedNumber(w.commitment_headroom,2)} · payments {fixedNumber(w.total_payments,2)} / headroom {fixedNumber(w.payment_headroom,2)} SAR</p>)}</details>
          <details><summary>Purchases, movements and forecast inspection · {o.policy}</summary><div tabIndex={0} role="region" aria-label="Scrollable table" className="table-scroll daily-table"><table><thead><tr><th>Action / SKU</th><th>From → to</th><th>Units</th><th>Dispatch / arrival</th><th>Evidence</th></tr></thead><tbody>{[...(o.purchases||[]),...(o.movements||[])].map(a=>{const target='supplier_id' in a?purchaseEvidenceTarget(o,a.action_id):undefined;const location='source' in a?a.destination:target?.location_id;return <tr key={a.action_id}><th>{a.action_id} · {a.sku}</th><td>{'source' in a?a.source:a.supplier_id} → {a.destination}</td><td>{a.units}</td><td>{a.dispatch_date} / {a.arrival_date}</td><td>{'supplier_id' in a&&<small>{evidenceTargetSummary(target)}</small>}<button data-evidence-location={location||'unavailable'} disabled={!location} onClick={()=>{if(location)inspect(o,a.sku,location,a.action_id);}}>Inspect action</button></td></tr>;})}</tbody></table></div></details>
          <details><summary>Remaining shortages and constraint evidence · {o.policy}</summary>{o.shortages.map(s=><p key={`${s.sku}/${s.location_id}`}><button onClick={()=>inspect(o,s.sku,s.location_id)}>{s.sku} / {s.location_id} forecast</button> · {number(s.unmet)} visible / {number(s.tail_unmet)} tail unmet</p>)}{o.explanations.map((f,i)=><p key={i}>{f.code} · {f.message}</p>)}{o.stages.map((s,i)=><p key={`stage${i}`}>{s.name} · {s.status}</p>)}</details>
        </section>)}
      </section>{evidence&&<ScenarioEvidence request={evidence} onClose={()=>setEvidence(null)} onForecast={onForecast}/>}
    </>}
  </>;
}
