import {test,expect,type Page} from '@playwright/test';

const wait=(page:Page,path:string)=>page.waitForResponse(r=>new URL(r.url()).pathname.endsWith(path)&&r.ok(),{timeout:60_000});

test('reviewed full-sample actions and provenance are the captured scenario baseline',async({page})=>{
  test.setTimeout(180_000);await page.goto('/');await expect(page.getByTestId('forecast-result')).toBeVisible();
  const fixturePlan=wait(page,'/api/plan/sample');await page.getByRole('button',{name:'Plan Review',exact:true}).click();await fixturePlan;
  const fullPlanResponse=wait(page,'/api/plan/sample');await page.getByLabel('Planning dataset').selectOption('full');const original=await(await fullPlanResponse).json();expect(original.provenance.sample_size).toBe('full');
  const controls=page.getByRole('region',{name:'Reviewed actions'});await expect(controls.getByRole('button',{name:'Apply quantity edit',exact:true})).toBeEnabled({timeout:15_000});const edited=original.proposed.purchases.find((p:{units:number})=>p.units>10);expect(edited).toBeTruthy();
  await controls.getByLabel('Action to review').selectOption(edited.action_id);await controls.getByLabel('Reviewed quantity').fill(String(edited.units-10));await controls.getByRole('button',{name:'Apply quantity edit',exact:true}).click();await expect(page.getByRole('button',{name:'Test disruptions with this baseline'})).toBeDisabled();await expect(page.getByRole('button',{name:'Scenarios',exact:true})).toBeDisabled();
  const regeneratedResponse=wait(page,'/regenerate');await controls.getByRole('button',{name:'Regenerate reviewed plan'}).click();const review=await(await regeneratedResponse).json();expect(review.failures).toEqual([]);expect(review.state).toBe('draft');await expect(controls.getByRole('button',{name:'Finally accept plan'})).toBeEnabled({timeout:15_000});
  const saved=await(await page.request.get(`/api/workflow/review/${review.reference}/plan`)).json();expect(saved.provenance.sample_size).toBe('full');expect(saved.proposed.purchases).not.toEqual(original.proposed.purchases);
  const captureRequest=page.waitForRequest(r=>new URL(r.url()).pathname==='/api/scenarios/capture');const captureResponse=wait(page,'/api/scenarios/capture');await page.getByRole('button',{name:'Test disruptions with this baseline'}).click();const payload=(await captureRequest).postDataJSON();const baseline=await(await captureResponse).json();
  expect(payload.size).toBe('full');expect(payload.dataset_hash).toBe(saved.input_hash);expect(payload.purchases).toEqual(saved.proposed.purchases);expect(payload.movements).toEqual(saved.proposed.movements);
  expect(baseline.baseline.size).toBe('full');expect(baseline.baseline.provenance).toEqual(saved.provenance);expect(baseline.original.purchases).toEqual(saved.proposed.purchases);expect(baseline.original.movements).toEqual(saved.proposed.movements);
});

test('scenario-derived reviewed plans cannot silently become a second baseline',async({page})=>{
  test.setTimeout(180_000);await page.goto('/');await expect(page.getByTestId('forecast-result')).toBeVisible();
  const planning=wait(page,'/api/plan/sample');await page.getByRole('button',{name:'Plan Review',exact:true}).click();const original=await(await planning).json();await expect(page.getByRole('button',{name:'Test disruptions with this baseline'})).toBeEnabled({timeout:15_000});
  const firstCaptureRequest=page.waitForRequest(r=>new URL(r.url()).pathname==='/api/scenarios/capture');const firstCapture=wait(page,'/api/scenarios/capture');await page.getByRole('button',{name:'Test disruptions with this baseline'}).click();const originalPayload=(await firstCaptureRequest).postDataJSON();await firstCapture;
  await page.getByRole('button',{name:'Promotion',exact:true}).click();const comparison=wait(page,'/api/scenarios/compare');await page.getByRole('button',{name:'Run scenario live',exact:true}).click();await comparison;
  const scenarioPlan=wait(page,'/api/workflow/scenario');await page.getByRole('button',{name:'Review replanned actions'}).click();await scenarioPlan;
  await expect(page.getByText('This reviewed plan already includes scenario assumptions.')).toBeVisible();await expect(page.getByRole('button',{name:'Test disruptions with this baseline'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Scenarios',exact:true})).toBeDisabled();
  const restoredCaptureRequest=page.waitForRequest(r=>new URL(r.url()).pathname==='/api/scenarios/capture');const restoredCapture=wait(page,'/api/scenarios/capture');await page.getByRole('button',{name:'Return to original scenario baseline'}).click();const restoredPayload=(await restoredCaptureRequest).postDataJSON();const restored=await(await restoredCapture).json();expect(restoredPayload).toEqual(originalPayload);expect(restored.original.purchases).toEqual(original.proposed.purchases);expect(restored.original.movements).toEqual(original.proposed.movements);
});

test('dataset reset prevents a late regenerated result from restoring abandoned state',async({page})=>{
  test.setTimeout(150_000);await page.goto('/');await expect(page.getByTestId('forecast-result')).toBeVisible();
  const firstPlan=wait(page,'/api/plan/sample');await page.getByRole('button',{name:'Plan Review',exact:true}).click();const oldPlan=await(await firstPlan).json();const controls=page.getByRole('region',{name:'Reviewed actions'});await controls.getByRole('button',{name:'Reject action',exact:true}).click();
  let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const delivered=new Promise<void>(resolve=>arrived=resolve);await page.route('**/api/workflow/review/*/plan',async route=>{const response=await route.fetch();arrived();await gate;try{await route.fulfill({response});}catch{/* Reset aborts this obsolete browser delivery. */}});
  await controls.getByRole('button',{name:'Regenerate reviewed plan'}).click();await delivered;await page.getByRole('button',{name:'Data and Assumptions',exact:true}).click();const reset=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/workflow/session'&&r.request().method()==='DELETE'&&r.ok());await page.getByRole('button',{name:'Reset to bundled sample'}).click();await reset;release();
  await expect(page.getByTestId('forecast-result')).toBeVisible();await page.unroute('**/api/workflow/review/*/plan');const freshResponse=wait(page,'/api/plan/sample');await page.getByRole('button',{name:'Plan Review',exact:true}).click();const fresh=await(await freshResponse).json();expect(fresh.run_id).not.toBe(oldPlan.run_id);await expect(page.getByTestId('plan-result')).toHaveAttribute('data-run-id',fresh.run_id);await expect(controls.getByRole('button',{name:'Load regenerated result'})).toHaveCount(0);
});

test('scenario-derived return cannot abandon a regeneration before its reference is recorded',async({page})=>{
  test.setTimeout(180_000);const failed:string[]=[];page.on('requestfailed',r=>{if(new URL(r.url()).pathname.endsWith('/regenerate'))failed.push(r.url());});
  await page.goto('/');await expect(page.getByTestId('forecast-result')).toBeVisible();const planning=wait(page,'/api/plan/sample');await page.getByRole('button',{name:'Plan Review',exact:true}).click();await planning;
  const capture=wait(page,'/api/scenarios/capture');await page.getByRole('button',{name:'Test disruptions with this baseline'}).click();await capture;await page.getByRole('button',{name:'Promotion',exact:true}).click();const comparison=wait(page,'/api/scenarios/compare');await page.getByRole('button',{name:'Run scenario live',exact:true}).click();await comparison;
  const scenarioPlan=wait(page,'/api/workflow/scenario');await page.getByRole('button',{name:'Review replanned actions'}).click();const derived=await(await scenarioPlan).json();const controls=page.getByRole('region',{name:'Reviewed actions'});await expect(controls.getByRole('button',{name:'Reject action',exact:true})).toBeEnabled({timeout:15_000});
  await controls.getByRole('button',{name:'Reject action',exact:true}).click();await expect(controls.getByRole('status').filter({hasText:'Plan state:'})).toContainText('stale');
  let requestedReplacement='';await page.route('**/api/workflow/review/*/plan',r=>{requestedReplacement=new URL(r.request().url()).pathname;return r.fulfill({status:503,json:{message:'Replacement result unavailable.'}});});
  let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const serverSaved=new Promise<void>(resolve=>arrived=resolve);await page.route('**/api/workflow/review/*/regenerate',async route=>{const response=await route.fetch();arrived();await gate;await route.fulfill({response});});
  const response=wait(page,'/regenerate');await controls.getByRole('button',{name:'Regenerate reviewed plan'}).click();await serverSaved;const returnButton=page.getByRole('button',{name:'Return to original scenario baseline'});await expect(returnButton).toBeDisabled();await expect(controls.getByRole('status').filter({hasText:'Saving review mutation'})).toBeVisible();
  await returnButton.evaluate((button:HTMLButtonElement)=>{button.disabled=false;button.click();});await expect(page.getByRole('heading',{name:'Plan Review'})).toBeVisible();await expect(page.getByTestId('plan-result')).toHaveAttribute('data-run-id',derived.run_id);expect(failed).toEqual([]);
  release();const saved=await(await response).json();await expect(controls.getByRole('alert')).toContainText('Replacement result unavailable.');expect(requestedReplacement).toContain(saved.reference);expect(failed).toEqual([]);await expect(returnButton).toBeEnabled();await expect(controls.getByRole('button',{name:'Load regenerated result'})).toBeVisible();
  const restored=wait(page,'/api/scenarios/capture');await returnButton.click();await restored;await expect(page.getByRole('heading',{name:'Scenarios'})).toBeVisible();
});

test('evidence forecast navigation waits until regeneration response records recovery',async({page})=>{
  test.setTimeout(150_000);const failed:string[]=[];page.on('requestfailed',r=>{if(new URL(r.url()).pathname.endsWith('/regenerate'))failed.push(r.url());});
  await page.goto('/');await expect(page.getByTestId('forecast-result')).toBeVisible();const planning=wait(page,'/api/plan/sample');await page.getByRole('button',{name:'Plan Review',exact:true}).click();await planning;const controls=page.getByRole('region',{name:'Reviewed actions'});await expect(controls.getByRole('button',{name:'Reject action',exact:true})).toBeEnabled({timeout:15_000});
  await controls.getByRole('button',{name:'Reject action',exact:true}).click();await expect(controls.getByRole('status').filter({hasText:'Plan state:'})).toContainText('stale');const row=page.getByTestId('purchase-table').locator('tbody tr').first();await row.locator('summary').click();const detail=wait(page,'/detail');await row.getByRole('button',{name:'Inspect purchase and forecast'}).click();await detail;const forecastButton=page.getByRole('button',{name:'Open this forecast in Demand Review'});await expect(forecastButton).toBeVisible();
  let requestedReplacement='';await page.route('**/api/workflow/review/*/plan',r=>{requestedReplacement=new URL(r.request().url()).pathname;return r.fulfill({status:503,json:{message:'Result delivery failed after reference save.'}});});let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const serverSaved=new Promise<void>(resolve=>arrived=resolve);await page.route('**/api/workflow/review/*/regenerate',async route=>{const response=await route.fetch();arrived();await gate;await route.fulfill({response});});
  const response=wait(page,'/regenerate');await controls.getByRole('button',{name:'Regenerate reviewed plan'}).click();await serverSaved;await expect(forecastButton).toBeDisabled();await forecastButton.evaluate((button:HTMLButtonElement)=>{button.disabled=false;button.click();});await expect(page.getByRole('heading',{name:'Plan Review'})).toBeVisible();expect(failed).toEqual([]);
  release();const saved=await(await response).json();await expect(controls.getByRole('alert')).toContainText('Result delivery failed after reference save.');expect(requestedReplacement).toContain(saved.reference);expect(failed).toEqual([]);await expect(forecastButton).toBeEnabled();await forecastButton.click();await expect(page.getByRole('heading',{name:'Demand Review'})).toBeVisible();
  await page.getByRole('button',{name:'Plan Review',exact:true}).click();await expect(controls.getByRole('button',{name:'Load regenerated result'})).toBeVisible();
});

test('first review mutation locks planning dataset and recalculation handlers',async({page})=>{
  test.setTimeout(90_000);let planRequests=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/plan/sample')planRequests++;});const failed:string[]=[];page.on('requestfailed',r=>{if(new URL(r.url()).pathname.endsWith('/decision'))failed.push(r.url());});
  await page.goto('/');await expect(page.getByTestId('forecast-result')).toBeVisible();const planning=wait(page,'/api/plan/sample');await page.getByRole('button',{name:'Plan Review',exact:true}).click();const original=await(await planning).json();const controls=page.getByRole('region',{name:'Reviewed actions'});await expect(controls.getByRole('button',{name:'Reject action',exact:true})).toBeEnabled({timeout:15_000});const selector=page.getByLabel('Planning dataset');const recalculate=page.getByRole('button',{name:'Recalculate plan'});await expect(selector).toBeEnabled();await expect(recalculate).toBeEnabled();
  const loadedReferences:string[]=[];page.on('request',r=>{const path=new URL(r.url()).pathname;if(r.method()==='GET'&&/^\/api\/workflow\/review\/[^/]+$/.test(path))loadedReferences.push(path);});let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let arrived!:()=>void;const serverSaved=new Promise<void>(resolve=>arrived=resolve);await page.route('**/api/workflow/review/*/decision',async route=>{const response=await route.fetch();arrived();await gate;await route.fulfill({response});});
  const decision=wait(page,'/decision');await controls.getByRole('button',{name:'Reject action',exact:true}).click();await serverSaved;await expect(selector).toBeDisabled();await expect(recalculate).toBeDisabled();await selector.evaluate((element:HTMLSelectElement)=>{element.disabled=false;element.value='full';element.dispatchEvent(new Event('change',{bubbles:true}));});await recalculate.evaluate((button:HTMLButtonElement)=>{button.disabled=false;button.click();});
  await expect(page.getByRole('heading',{name:'Plan Review'})).toBeVisible();await expect(page.getByTestId('plan-result')).toHaveAttribute('data-run-id',original.run_id);expect(planRequests).toBe(1);expect(failed).toEqual([]);release();const saved=await(await decision).json();await expect(controls.getByRole('status').filter({hasText:'Plan state:'})).toContainText('stale');await expect.poll(()=>loadedReferences.some(path=>path.endsWith(`/${saved.reference}`))).toBe(true);expect(failed).toEqual([]);expect(planRequests).toBe(1);
});
